export default [
  {
    name: "Blueprint 1",
    oreBot: { ore: 3 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 3, clay: 18 },
    geodeBot: { ore: 4, obsidian: 19 },
  },
  {
    name: "Blueprint 2",
    oreBot: { ore: 2 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 3, clay: 19 },
    geodeBot: { ore: 4, obsidian: 12 },
  },
  {
    name: "Blueprint 3",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 12 },
    geodeBot: { ore: 3, obsidian: 8 },
  },
  {
    name: "Blueprint 4",
    oreBot: { ore: 2 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 3, clay: 19 },
    geodeBot: { ore: 4, obsidian: 13 },
  },
  {
    name: "Blueprint 5",
    oreBot: { ore: 2 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 3, clay: 17 },
    geodeBot: { ore: 3, obsidian: 10 },
  },
  {
    name: "Blueprint 6",
    oreBot: { ore: 3 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 3, clay: 17 },
    geodeBot: { ore: 4, obsidian: 8 },
  },
  {
    name: "Blueprint 7",
    oreBot: { ore: 4 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 3, clay: 7 },
    geodeBot: { ore: 2, obsidian: 7 },
  },
  {
    name: "Blueprint 8",
    oreBot: { ore: 3 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 6 },
    geodeBot: { ore: 3, obsidian: 16 },
  },
  {
    name: "Blueprint 9",
    oreBot: { ore: 3 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 3, clay: 19 },
    geodeBot: { ore: 3, obsidian: 17 },
  },
  {
    name: "Blueprint 10",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 9 },
    geodeBot: { ore: 4, obsidian: 16 },
  },
  {
    name: "Blueprint 11",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 2, clay: 7 },
    geodeBot: { ore: 4, obsidian: 18 },
  },
  {
    name: "Blueprint 12",
    oreBot: { ore: 3 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 3, clay: 20 },
    geodeBot: { ore: 2, obsidian: 12 },
  },
  {
    name: "Blueprint 13",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 3, clay: 5 },
    geodeBot: { ore: 3, obsidian: 18 },
  },
  {
    name: "Blueprint 14",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 3, clay: 7 },
    geodeBot: { ore: 4, obsidian: 11 },
  },
  {
    name: "Blueprint 15",
    oreBot: { ore: 4 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 2, clay: 14 },
    geodeBot: { ore: 2, obsidian: 7 },
  },
  {
    name: "Blueprint 16",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 3, clay: 7 },
    geodeBot: { ore: 3, obsidian: 20 },
  },
  {
    name: "Blueprint 17",
    oreBot: { ore: 2 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 18 },
    geodeBot: { ore: 2, obsidian: 11 },
  },
  {
    name: "Blueprint 18",
    oreBot: { ore: 2 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 17 },
    geodeBot: { ore: 3, obsidian: 11 },
  },
  {
    name: "Blueprint 19",
    oreBot: { ore: 2 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 2, clay: 20 },
    geodeBot: { ore: 2, obsidian: 17 },
  },
  {
    name: "Blueprint 20",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 5 },
    geodeBot: { ore: 3, obsidian: 7 },
  },
  {
    name: "Blueprint 21",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 15 },
    geodeBot: { ore: 4, obsidian: 17 },
  },
  {
    name: "Blueprint 22",
    oreBot: { ore: 4 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 3, clay: 15 },
    geodeBot: { ore: 2, obsidian: 13 },
  },
  {
    name: "Blueprint 23",
    oreBot: { ore: 3 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 2, clay: 16 },
    geodeBot: { ore: 3, obsidian: 14 },
  },
  {
    name: "Blueprint 24",
    oreBot: { ore: 4 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 4, clay: 5 },
    geodeBot: { ore: 3, obsidian: 10 },
  },
  {
    name: "Blueprint 25",
    oreBot: { ore: 3 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 2, clay: 20 },
    geodeBot: { ore: 2, obsidian: 20 },
  },
  {
    name: "Blueprint 26",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 14 },
    geodeBot: { ore: 2, obsidian: 16 },
  },
  {
    name: "Blueprint 27",
    oreBot: { ore: 3 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 8 },
    geodeBot: { ore: 2, obsidian: 10 },
  },
  {
    name: "Blueprint 28",
    oreBot: { ore: 3 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 3, clay: 8 },
    geodeBot: { ore: 2, obsidian: 12 },
  },
  {
    name: "Blueprint 29",
    oreBot: { ore: 4 },
    clayBot: { ore: 4 },
    obsidianBot: { ore: 4, clay: 8 },
    geodeBot: { ore: 2, obsidian: 15 },
  },
  {
    name: "Blueprint 30",
    oreBot: { ore: 3 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 2, clay: 7 },
    geodeBot: { ore: 2, obsidian: 9 },
  },
]

export const sample = [
  {
    name: "Blueprint 1",
    oreBot: { ore: 4 },
    clayBot: { ore: 2 },
    obsidianBot: { ore: 3, clay: 14 },
    geodeBot: { ore: 2, obsidian: 7 },
  },
  {
    name: "Blueprint 2",
    oreBot: { ore: 2 },
    clayBot: { ore: 3 },
    obsidianBot: { ore: 3, clay: 8 },
    geodeBot: { ore: 3, obsidian: 12 },
  },
]
