export default [
  ["dr", "of"],
  ["start", "KT"],
  ["yj", "sk"],
  ["start", "gb"],
  ["of", "start"],
  ["IJ", "end"],
  ["VT", "sk"],
  ["end", "sk"],
  ["VT", "km"],
  ["KT", "end"],
  ["IJ", "of"],
  ["dr", "IJ"],
  ["yj", "IJ"],
  ["KT", "yj"],
  ["gb", "VT"],
  ["dr", "yj"],
  ["VT", "of"],
  ["PZ", "dr"],
  ["KT", "of"],
  ["KT", "gb"],
  ["of", "gb"],
  ["dr", "sk"],
  ["dr", "VT"],
]

export const sample = [
  ["dc", "end"],
  ["HN", "start"],
  ["start", "kj"],
  ["dc", "start"],
  ["dc", "HN"],
  ["LN", "dc"],
  ["HN", "end"],
  ["kj", "sa"],
  ["kj", "HN"],
  ["kj", "dc"],
]
