export default [
  ["dr", "of"],
  ["start", "KT"],
  ["yj", "sk"],
  ["start", "gb"],
  ["of", "start"],
  ["IJ", "end"],
  ["VT", "sk"],
  ["end", "sk"],
  ["VT", "km"],
  ["KT", "end"],
  ["IJ", "of"],
  ["dr", "IJ"],
  ["yj", "IJ"],
  ["KT", "yj"],
  ["gb", "VT"],
  ["dr", "yj"],
  ["VT", "of"],
  ["PZ", "dr"],
  ["KT", "of"],
  ["KT", "gb"],
  ["of", "gb"],
  ["dr", "sk"],
  ["dr", "VT"],
]

export const smallSample = [
  ["start", "A"],
  ["start", "b"],
  ["A", "c"],
  ["A", "b"],
  ["b", "d"],
  ["A", "end"],
  ["b", "end"],
]

export const sample = [
  ["fs", "end"],
  ["he", "DX"],
  ["fs", "he"],
  ["start", "DX"],
  ["pj", "DX"],
  ["end", "zg"],
  ["zg", "sl"],
  ["zg", "pj"],
  ["pj", "he"],
  ["RW", "he"],
  ["fs", "DX"],
  ["pj", "RW"],
  ["zg", "RW"],
  ["start", "pj"],
  ["he", "WI"],
  ["zg", "he"],
  ["pj", "fs"],
  ["start", "RW"],
]
