export default [
  { node: "TU", flowRate: 0, nodes: ["XG", "ID"] },
  { node: "RR", flowRate: 0, nodes: ["BO", "NF"] },
  { node: "UB", flowRate: 0, nodes: ["GY", "AC"] },
  { node: "OP", flowRate: 0, nodes: ["OU", "DI"] },
  { node: "KL", flowRate: 21, nodes: ["QZ", "QT"] },
  { node: "QA", flowRate: 0, nodes: ["AC", "XM"] },
  { node: "CI", flowRate: 0, nodes: ["RH", "BC"] },
  { node: "NZ", flowRate: 0, nodes: ["TO", "OU"] },
  { node: "MY", flowRate: 0, nodes: ["BO", "KV"] },
  { node: "GY", flowRate: 0, nodes: ["KW", "UB"] },
  { node: "ZB", flowRate: 0, nodes: ["YS", "XH"] },
  { node: "OU", flowRate: 8, nodes: ["ZV", "YA", "NZ", "OP"] },
  { node: "KV", flowRate: 0, nodes: ["MJ", "MY"] },
  { node: "BC", flowRate: 0, nodes: ["TO", "CI"] },
  { node: "YS", flowRate: 22, nodes: ["ZB", "UE"] },
  { node: "CD", flowRate: 25, nodes: ["LS", "FO"] },
  { node: "ID", flowRate: 11, nodes: ["BI", "TU"] },
  { node: "RN", flowRate: 0, nodes: ["AC", "CN"] },
  { node: "HH", flowRate: 0, nodes: ["GI", "KW"] },
  { node: "QZ", flowRate: 0, nodes: ["AC", "KL"] },
  { node: "BI", flowRate: 0, nodes: ["OI", "ID"] },
  { node: "NF", flowRate: 0, nodes: ["RR", "OI"] },
  { node: "CH", flowRate: 0, nodes: ["AA", "MJ"] },
  { node: "UE", flowRate: 0, nodes: ["LS", "YS"] },
  { node: "ZV", flowRate: 0, nodes: ["OU", "AA"] },
  { node: "YM", flowRate: 0, nodes: ["OI", "AA"] },
  { node: "IG", flowRate: 0, nodes: ["TO", "QL"] },
  { node: "FO", flowRate: 0, nodes: ["CD", "KW"] },
  { node: "AC", flowRate: 4, nodes: ["KC", "RN", "QA", "QZ", "UB"] },
  { node: "JO", flowRate: 0, nodes: ["RH", "DI"] },
  { node: "OI", flowRate: 10, nodes: ["VS", "BI", "CN", "NF", "YM"] },
  { node: "MJ", flowRate: 3, nodes: ["KV", "XM", "ER", "CH", "BS"] },
  { node: "KC", flowRate: 0, nodes: ["AC", "AA"] },
  { node: "ER", flowRate: 0, nodes: ["MJ", "VS"] },
  { node: "CV", flowRate: 0, nodes: ["TO", "IU"] },
  { node: "RW", flowRate: 0, nodes: ["DT", "QT"] },
  { node: "CN", flowRate: 0, nodes: ["OI", "RN"] },
  { node: "IU", flowRate: 0, nodes: ["DY", "CV"] },
  { node: "LS", flowRate: 0, nodes: ["CD", "UE"] },
  { node: "AA", flowRate: 0, nodes: ["CH", "KC", "YM", "ZV", "GI"] },
  { node: "DY", flowRate: 23, nodes: ["IU", "ZP"] },
  { node: "BS", flowRate: 0, nodes: ["MJ", "KW"] },
  { node: "XG", flowRate: 0, nodes: ["TU", "BO"] },
  { node: "RH", flowRate: 15, nodes: ["HK", "JO", "CI"] },
  { node: "BO", flowRate: 18, nodes: ["MY", "XG", "RR"] },
  { node: "YA", flowRate: 0, nodes: ["OU", "HK"] },
  { node: "VS", flowRate: 0, nodes: ["OI", "ER"] },
  { node: "KW", flowRate: 6, nodes: ["BS", "XH", "GY", "HH", "FO"] },
  { node: "XH", flowRate: 0, nodes: ["ZB", "KW"] },
  { node: "ZP", flowRate: 0, nodes: ["DY", "DI"] },
  { node: "QL", flowRate: 0, nodes: ["DI", "IG"] },
  { node: "GI", flowRate: 0, nodes: ["HH", "AA"] },
  { node: "DT", flowRate: 24, nodes: ["RW"] },
  { node: "DI", flowRate: 13, nodes: ["OP", "ZP", "JO", "QL"] },
  { node: "QT", flowRate: 0, nodes: ["RW", "KL"] },
  { node: "XM", flowRate: 0, nodes: ["QA", "MJ"] },
  { node: "HK", flowRate: 0, nodes: ["RH", "YA"] },
  { node: "TO", flowRate: 19, nodes: ["NZ", "IG", "BC", "CV"] },
]

export const sample = [
  { node: "AA", flowRate: 0, nodes: ["DD", "II", "BB"] },
  { node: "BB", flowRate: 13, nodes: ["CC", "AA"] },
  { node: "CC", flowRate: 2, nodes: ["DD", "BB"] },
  { node: "DD", flowRate: 20, nodes: ["CC", "AA", "EE"] },
  { node: "EE", flowRate: 3, nodes: ["FF", "DD"] },
  { node: "FF", flowRate: 0, nodes: ["EE", "GG"] },
  { node: "GG", flowRate: 0, nodes: ["FF", "HH"] },
  { node: "HH", flowRate: 22, nodes: ["GG"] },
  { node: "II", flowRate: 0, nodes: ["AA", "JJ"] },
  { node: "JJ", flowRate: 21, nodes: ["II"] },
]
