export default [
  { id: "fnsw", val: "vlmz - lssm", deps: ["vlmz", "lssm"] },
  { id: "gwlv", val: 2 },
  { id: "zcsz", val: "lcwg * sfsg", deps: ["lcwg", "sfsg"] },
  { id: "zdrm", val: 3 },
  { id: "bpzq", val: 1 },
  { id: "jvvs", val: "cfwg + mgdb", deps: ["cfwg", "mgdb"] },
  { id: "wjvb", val: 2 },
  { id: "gspq", val: 3 },
  { id: "thbm", val: "csnh * vqlg", deps: ["csnh", "vqlg"] },
  { id: "zwjj", val: "svzn + znpl", deps: ["svzn", "znpl"] },
  { id: "qfnv", val: "fmzc * wgtv", deps: ["fmzc", "wgtv"] },
  { id: "hjln", val: "tsdf * hwjh", deps: ["tsdf", "hwjh"] },
  { id: "dflj", val: "qdgp * cvjw", deps: ["qdgp", "cvjw"] },
  { id: "jsqj", val: 2 },
  { id: "jsdl", val: "lfdn / cffd", deps: ["lfdn", "cffd"] },
  { id: "hzmf", val: 7 },
  { id: "vswb", val: "sdrv + qwrs", deps: ["sdrv", "qwrs"] },
  { id: "vzwg", val: 3 },
  { id: "mhjm", val: 2 },
  { id: "nhzl", val: "mdsf * rmtj", deps: ["mdsf", "rmtj"] },
  { id: "qdhg", val: "tzwn * ndrb", deps: ["tzwn", "ndrb"] },
  { id: "cbzd", val: 11 },
  { id: "drhm", val: 1 },
  { id: "vjvt", val: 7 },
  { id: "fmbj", val: "nlhd + gprq", deps: ["nlhd", "gprq"] },
  { id: "sfpq", val: "rhhv * wcgt", deps: ["rhhv", "wcgt"] },
  { id: "vjdg", val: 2 },
  { id: "dlct", val: "dnzp * bcdp", deps: ["dnzp", "bcdp"] },
  { id: "chfd", val: 3 },
  { id: "jdjb", val: "dfrm + czjm", deps: ["dfrm", "czjm"] },
  { id: "ccsr", val: "nwzw + bfcp", deps: ["nwzw", "bfcp"] },
  { id: "wssm", val: 2 },
  { id: "hjss", val: "gncn * slgs", deps: ["gncn", "slgs"] },
  { id: "mfwn", val: "wrnb + zqsl", deps: ["wrnb", "zqsl"] },
  { id: "qlgj", val: "clcj + pbwc", deps: ["clcj", "pbwc"] },
  { id: "nrnw", val: 4 },
  { id: "mftc", val: 5 },
  { id: "nbrt", val: 3 },
  { id: "gcpq", val: "rdlm * jnvz", deps: ["rdlm", "jnvz"] },
  { id: "mgwl", val: 5 },
  { id: "swvr", val: 5 },
  { id: "zjmv", val: "scvc + gsjc", deps: ["scvc", "gsjc"] },
  { id: "nngq", val: "tqmc / qhjs", deps: ["tqmc", "qhjs"] },
  { id: "pnpc", val: 2 },
  { id: "rpgl", val: 5 },
  { id: "srls", val: "jddm + bmgz", deps: ["jddm", "bmgz"] },
  { id: "prbq", val: "qdzj * qhvj", deps: ["qdzj", "qhvj"] },
  { id: "srzb", val: 3 },
  { id: "mwqn", val: "dbsp + csmb", deps: ["dbsp", "csmb"] },
  { id: "qwjn", val: "dtff * gspq", deps: ["dtff", "gspq"] },
  { id: "mvvj", val: 3 },
  { id: "qfrm", val: 9 },
  { id: "clbj", val: "tnvv * zfvl", deps: ["tnvv", "zfvl"] },
  { id: "vvlr", val: 2 },
  { id: "dlrn", val: "mpfr + vrzm", deps: ["mpfr", "vrzm"] },
  { id: "zrdh", val: 7 },
  { id: "lmdh", val: "qrqp * blgz", deps: ["qrqp", "blgz"] },
  { id: "pfrn", val: "lnpm * qrnh", deps: ["lnpm", "qrnh"] },
  { id: "hrtg", val: 5 },
  { id: "lljf", val: 2 },
  { id: "wfvl", val: 3 },
  { id: "jnjr", val: 9 },
  { id: "lnpm", val: "tcgb + pppg", deps: ["tcgb", "pppg"] },
  { id: "dcws", val: 3 },
  { id: "spjg", val: 4 },
  { id: "pmnj", val: "rjmz * pdhw", deps: ["rjmz", "pdhw"] },
  { id: "zcvd", val: "hbws * gwlg", deps: ["hbws", "gwlg"] },
  { id: "pfbv", val: "pzfv * hcwj", deps: ["pzfv", "hcwj"] },
  { id: "jdqr", val: 5 },
  { id: "jshf", val: "mqhs + jwlt", deps: ["mqhs", "jwlt"] },
  { id: "pwrl", val: 2 },
  { id: "qchw", val: "hrvd - wsrw", deps: ["hrvd", "wsrw"] },
  { id: "fspc", val: "nbsp + btfc", deps: ["nbsp", "btfc"] },
  { id: "wvrt", val: "sstw * fhhc", deps: ["sstw", "fhhc"] },
  { id: "qgrw", val: "mhvf + zcgs", deps: ["mhvf", "zcgs"] },
  { id: "ncjq", val: "zhhj * dwtn", deps: ["zhhj", "dwtn"] },
  { id: "zwmc", val: 2 },
  { id: "rzqh", val: "lgqz + wfwh", deps: ["lgqz", "wfwh"] },
  { id: "hrpv", val: "qlml * pfrf", deps: ["qlml", "pfrf"] },
  { id: "rdgj", val: "rvhf + bwmt", deps: ["rvhf", "bwmt"] },
  { id: "pqvb", val: 16 },
  { id: "jsdj", val: "bhcp + zmbs", deps: ["bhcp", "zmbs"] },
  { id: "dglb", val: "vbns * glfs", deps: ["vbns", "glfs"] },
  { id: "nrjd", val: 2 },
  { id: "cvqs", val: 5 },
  { id: "zjzn", val: 2 },
  { id: "nthp", val: "nlps + nvzr", deps: ["nlps", "nvzr"] },
  { id: "rjst", val: 3 },
  { id: "jfnm", val: 6 },
  { id: "nldq", val: 3 },
  { id: "bnsl", val: 5 },
  { id: "tdvn", val: "vmvg * nvzn", deps: ["vmvg", "nvzn"] },
  { id: "wbqd", val: 10 },
  { id: "pwtn", val: 9 },
  { id: "bccr", val: "gglp + pvfw", deps: ["gglp", "pvfw"] },
  { id: "qwmb", val: 12 },
  { id: "spbm", val: "jwnd * zndn", deps: ["jwnd", "zndn"] },
  { id: "pjfv", val: 2 },
  { id: "chgr", val: 3 },
  { id: "zlvb", val: "gzmd + dvzp", deps: ["gzmd", "dvzp"] },
  { id: "jnjb", val: 4 },
  { id: "gprq", val: "mfrp - jlpf", deps: ["mfrp", "jlpf"] },
  { id: "lvsm", val: 4 },
  { id: "nbsp", val: 5 },
  { id: "pcpc", val: 5 },
  { id: "gtnl", val: "bhml * pjbl", deps: ["bhml", "pjbl"] },
  { id: "sbsl", val: 10 },
  { id: "sstt", val: 8 },
  { id: "trsz", val: 9 },
  { id: "snsb", val: "lsgm - qpfg", deps: ["lsgm", "qpfg"] },
  { id: "jncn", val: "vmhg * jmcs", deps: ["vmhg", "jmcs"] },
  { id: "vfrg", val: 2 },
  { id: "pqvt", val: 6 },
  { id: "vvgm", val: 15 },
  { id: "ptvf", val: "lczq * pwwr", deps: ["lczq", "pwwr"] },
  { id: "wwwm", val: "rspn / dmmp", deps: ["rspn", "dmmp"] },
  { id: "qfvs", val: 8 },
  { id: "bfdn", val: "lgtl + hglj", deps: ["lgtl", "hglj"] },
  { id: "nvmd", val: "tlqv + zcwt", deps: ["tlqv", "zcwt"] },
  { id: "gvrr", val: 3 },
  { id: "fqjz", val: 2 },
  { id: "gvjr", val: 2 },
  { id: "fsrb", val: 2 },
  { id: "wlbz", val: 5 },
  { id: "nnfq", val: "flhj + pwld", deps: ["flhj", "pwld"] },
  { id: "sdpz", val: "grcr / vszn", deps: ["grcr", "vszn"] },
  { id: "vvfm", val: 7 },
  { id: "wvlm", val: "fbmn - hwsh", deps: ["fbmn", "hwsh"] },
  { id: "gcrv", val: 7 },
  { id: "fvvq", val: "zlpd * sphs", deps: ["zlpd", "sphs"] },
  { id: "cbcf", val: 6 },
  { id: "fmgp", val: 2 },
  { id: "lnqb", val: "lqbn * vvmc", deps: ["lqbn", "vvmc"] },
  { id: "ttch", val: 8 },
  { id: "szzn", val: "mmtj * dvdm", deps: ["mmtj", "dvdm"] },
  { id: "rmtj", val: 3 },
  { id: "hhnc", val: "ccsm / lqml", deps: ["ccsm", "lqml"] },
  { id: "npvf", val: "mdws * jmzj", deps: ["mdws", "jmzj"] },
  { id: "wpzq", val: "hdsz * bgsh", deps: ["hdsz", "bgsh"] },
  { id: "gsjc", val: "zszn + qwdt", deps: ["zszn", "qwdt"] },
  { id: "lhfl", val: 2 },
  { id: "mrwt", val: "mdhd * vbvd", deps: ["mdhd", "vbvd"] },
  { id: "vfbq", val: "nmzb / vdlm", deps: ["nmzb", "vdlm"] },
  { id: "dscl", val: 5 },
  { id: "qblq", val: "wlpd * pjvz", deps: ["wlpd", "pjvz"] },
  { id: "grhp", val: "zcgt / fwbg", deps: ["zcgt", "fwbg"] },
  { id: "lhnj", val: "pzws * ptml", deps: ["pzws", "ptml"] },
  { id: "tjbr", val: "wbvd / sltr", deps: ["wbvd", "sltr"] },
  { id: "ffmj", val: "pwmp * qsbs", deps: ["pwmp", "qsbs"] },
  { id: "vbjg", val: 5 },
  { id: "wtms", val: 2 },
  { id: "zzhw", val: 10 },
  { id: "dgmp", val: "nptm + rhsb", deps: ["nptm", "rhsb"] },
  { id: "gqll", val: 5 },
  { id: "shhf", val: 5 },
  { id: "slgs", val: 20 },
  { id: "nqbh", val: "rwpl / bngl", deps: ["rwpl", "bngl"] },
  { id: "bqhg", val: 5 },
  { id: "dfzh", val: "vdnj * cqjc", deps: ["vdnj", "cqjc"] },
  { id: "rdvw", val: "fgzm * wzrg", deps: ["fgzm", "wzrg"] },
  { id: "bvrz", val: "mnvz - zgtj", deps: ["mnvz", "zgtj"] },
  { id: "mswd", val: 2 },
  { id: "hvrb", val: "prpb * cvlm", deps: ["prpb", "cvlm"] },
  { id: "ffmz", val: "tfcq + flrz", deps: ["tfcq", "flrz"] },
  { id: "wgdp", val: 17 },
  { id: "lwgt", val: "jmwr + vscz", deps: ["jmwr", "vscz"] },
  { id: "zbcv", val: 4 },
  { id: "jqvv", val: "rcsw * hwpm", deps: ["rcsw", "hwpm"] },
  { id: "sftj", val: 2 },
  { id: "prvl", val: "gpws * cgdn", deps: ["gpws", "cgdn"] },
  { id: "jmcs", val: 2 },
  { id: "djsf", val: "stsw / jvgg", deps: ["stsw", "jvgg"] },
  { id: "slwq", val: "vgdd * vnmg", deps: ["vgdd", "vnmg"] },
  { id: "hppl", val: 5 },
  { id: "rcgh", val: "cgtn + brtw", deps: ["cgtn", "brtw"] },
  { id: "dnrd", val: "lhlp + tgjh", deps: ["lhlp", "tgjh"] },
  { id: "prpw", val: "jfbt + vszs", deps: ["jfbt", "vszs"] },
  { id: "ccjt", val: "wmcv - rbqp", deps: ["wmcv", "rbqp"] },
  { id: "gqlj", val: "cczr * nthp", deps: ["cczr", "nthp"] },
  { id: "tfnc", val: 12 },
  { id: "qcdv", val: 16 },
  { id: "gdpf", val: 3 },
  { id: "wtwl", val: "jgcn * nnjl", deps: ["jgcn", "nnjl"] },
  { id: "vgqr", val: 5 },
  { id: "hfjg", val: "lzjb + nngq", deps: ["lzjb", "nngq"] },
  { id: "qlzp", val: 2 },
  { id: "hjdb", val: 2 },
  { id: "hbsq", val: 2 },
  { id: "zpdl", val: "nfvl * dfwb", deps: ["nfvl", "dfwb"] },
  { id: "sqwc", val: 3 },
  { id: "gdrz", val: 4 },
  { id: "rncs", val: "cnmf / psqh", deps: ["cnmf", "psqh"] },
  { id: "czlm", val: 7 },
  { id: "sdrt", val: 2 },
  { id: "hfws", val: "mjvp * bqzt", deps: ["mjvp", "bqzt"] },
  { id: "tcml", val: 2 },
  { id: "gzbq", val: "hbdn + nqfb", deps: ["hbdn", "nqfb"] },
  { id: "mlrn", val: "gwvh * lgff", deps: ["gwvh", "lgff"] },
  { id: "svng", val: "rjcr * fwss", deps: ["rjcr", "fwss"] },
  { id: "wmzv", val: "rzfm + gphl", deps: ["rzfm", "gphl"] },
  { id: "chws", val: "hmmg / nrjd", deps: ["hmmg", "nrjd"] },
  { id: "wzrg", val: "ldsn - smjn", deps: ["ldsn", "smjn"] },
  { id: "bsnt", val: "nbpj + shsd", deps: ["nbpj", "shsd"] },
  { id: "fvmb", val: "wzth + nlnq", deps: ["wzth", "nlnq"] },
  { id: "mqhs", val: "dncb + vjpw", deps: ["dncb", "vjpw"] },
  { id: "ncvj", val: "ndwb * wgdp", deps: ["ndwb", "wgdp"] },
  { id: "pdhw", val: 2 },
  { id: "zdzp", val: 2 },
  { id: "rzlc", val: 2 },
  { id: "trhb", val: "sdws + bjct", deps: ["sdws", "bjct"] },
  { id: "hztt", val: 2 },
  { id: "ctgh", val: 4 },
  { id: "lfft", val: "pmnp + lwsf", deps: ["pmnp", "lwsf"] },
  { id: "gbgr", val: 2 },
  { id: "msfw", val: 3 },
  { id: "rgcj", val: 6 },
  { id: "vbnt", val: 8 },
  { id: "pvcq", val: "fwqj * nzfv", deps: ["fwqj", "nzfv"] },
  { id: "dwwz", val: "qlzp + dntd", deps: ["qlzp", "dntd"] },
  { id: "smjn", val: "grhp * chws", deps: ["grhp", "chws"] },
  { id: "qhvj", val: "jcvq + ggcc", deps: ["jcvq", "ggcc"] },
  { id: "qpsr", val: "hppq + grcl", deps: ["hppq", "grcl"] },
  { id: "cvjw", val: "lnqb / bqnv", deps: ["lnqb", "bqnv"] },
  { id: "wgvf", val: "csqb * ttqg", deps: ["csqb", "ttqg"] },
  { id: "zlbl", val: "lgrn * dqbf", deps: ["lgrn", "dqbf"] },
  { id: "zmdq", val: 6 },
  { id: "cgqw", val: 2 },
  { id: "ngbs", val: 3 },
  { id: "pjnz", val: 7 },
  { id: "ddlw", val: 4 },
  { id: "vgdd", val: "wtjh + ngrp", deps: ["wtjh", "ngrp"] },
  { id: "zzts", val: 3 },
  { id: "vjrf", val: "bcjv * mjzj", deps: ["bcjv", "mjzj"] },
  { id: "vcbr", val: 5 },
  { id: "vnfp", val: "hjgc + nfvb", deps: ["hjgc", "nfvb"] },
  { id: "zdlm", val: "hzmf * lwlq", deps: ["hzmf", "lwlq"] },
  { id: "rbqp", val: 12 },
  { id: "ctzs", val: 15 },
  { id: "cbld", val: "smwh + lbbp", deps: ["smwh", "lbbp"] },
  { id: "smhj", val: 6 },
  { id: "qpfg", val: 4 },
  { id: "qnfh", val: 3 },
  { id: "nndw", val: 3 },
  { id: "fprl", val: "tvpl + hjdb", deps: ["tvpl", "hjdb"] },
  { id: "nhgf", val: "ltft + rdgj", deps: ["ltft", "rdgj"] },
  { id: "hmmg", val: "tbfn * scrn", deps: ["tbfn", "scrn"] },
  { id: "fbcm", val: "pczl * jzch", deps: ["pczl", "jzch"] },
  { id: "mgrz", val: 2 },
  { id: "wppg", val: 3 },
  { id: "fwjp", val: "wgvf * sdrt", deps: ["wgvf", "sdrt"] },
  { id: "dtgc", val: 4 },
  { id: "hvqs", val: "zzsq * tfmb", deps: ["zzsq", "tfmb"] },
  { id: "fzjj", val: 8 },
  { id: "vlfd", val: 4 },
  { id: "wbdz", val: "fnlz + rnzj", deps: ["fnlz", "rnzj"] },
  { id: "hjgc", val: 2 },
  { id: "svjj", val: 6 },
  { id: "wndc", val: "cmwr * mcnm", deps: ["cmwr", "mcnm"] },
  { id: "nnph", val: 10 },
  { id: "twvq", val: "cpvs - cbld", deps: ["cpvs", "cbld"] },
  { id: "wqzj", val: 5 },
  { id: "ltlm", val: 19 },
  { id: "hpcq", val: 4 },
  { id: "mnzn", val: 4 },
  { id: "hwfz", val: "nhpl * wzgw", deps: ["nhpl", "wzgw"] },
  { id: "wqnn", val: 8 },
  { id: "mwgg", val: "rjst + bsjc", deps: ["rjst", "bsjc"] },
  { id: "mbbt", val: 6 },
  { id: "zlsl", val: "nwpf + ffmj", deps: ["nwpf", "ffmj"] },
  { id: "ptml", val: 4 },
  { id: "pshc", val: 2 },
  { id: "nlnq", val: 1 },
  { id: "dvzp", val: "wzql * wtnv", deps: ["wzql", "wtnv"] },
  { id: "rmhr", val: 2 },
  { id: "bmjd", val: 3 },
  { id: "zfcd", val: "ttqw * qcpl", deps: ["ttqw", "qcpl"] },
  { id: "nslm", val: "wtms + qwjb", deps: ["wtms", "qwjb"] },
  { id: "mbll", val: 2 },
  { id: "bjml", val: 3 },
  { id: "fdlb", val: "hgvc * zttg", deps: ["hgvc", "zttg"] },
  { id: "bqnv", val: 5 },
  { id: "wznd", val: "zgqq - hvrb", deps: ["zgqq", "hvrb"] },
  { id: "lbfn", val: 3 },
  { id: "njwq", val: "cbdq * ddhj", deps: ["cbdq", "ddhj"] },
  { id: "mqvs", val: "bvll * bnsl", deps: ["bvll", "bnsl"] },
  { id: "jgcn", val: 4 },
  { id: "rdgm", val: "cbcb + qwjn", deps: ["cbcb", "qwjn"] },
  { id: "vpqv", val: "wvrt / hczz", deps: ["wvrt", "hczz"] },
  { id: "gvcw", val: 9 },
  { id: "qznr", val: 11 },
  { id: "smwh", val: 6 },
  { id: "cvml", val: 5 },
  { id: "rwpl", val: "gbtq + mbzh", deps: ["gbtq", "mbzh"] },
  { id: "ncgl", val: 4 },
  { id: "nrqr", val: "ssqn * hztt", deps: ["ssqn", "hztt"] },
  { id: "zspc", val: 2 },
  { id: "qcsd", val: 11 },
  { id: "wblt", val: 2 },
  { id: "bqgf", val: 10 },
  { id: "fmhc", val: "wlfc + cpnh", deps: ["wlfc", "cpnh"] },
  { id: "snlm", val: "jhmp * qdcp", deps: ["jhmp", "qdcp"] },
  { id: "qrrw", val: 3 },
  { id: "vrwm", val: "cczz + rqht", deps: ["cczz", "rqht"] },
  { id: "bmgz", val: "rjgb * vwzz", deps: ["rjgb", "vwzz"] },
  { id: "vzzj", val: 4 },
  { id: "gltp", val: "nnpd * sfqw", deps: ["nnpd", "sfqw"] },
  { id: "rvrr", val: "wwwm * lvms", deps: ["wwwm", "lvms"] },
  { id: "brtw", val: 5 },
  { id: "vscz", val: 9 },
  { id: "hzdl", val: 2 },
  { id: "lfbv", val: "ccsr + jjwn", deps: ["ccsr", "jjwn"] },
  { id: "vhmq", val: "dlbb * drzm", deps: ["dlbb", "drzm"] },
  { id: "pswb", val: 5 },
  { id: "vrtr", val: 2 },
  { id: "blgz", val: 12 },
  { id: "pcfg", val: 3 },
  { id: "mdlj", val: 5 },
  { id: "cwcd", val: "fqfs / jjgc", deps: ["fqfs", "jjgc"] },
  { id: "lvtf", val: 3 },
  { id: "cfhr", val: 7 },
  { id: "twml", val: "bsnf + vggn", deps: ["bsnf", "vggn"] },
  { id: "vhcd", val: "npwm + vlfd", deps: ["npwm", "vlfd"] },
  { id: "smcc", val: "wjnl * ddjr", deps: ["wjnl", "ddjr"] },
  { id: "rvhf", val: "jspb / gwvz", deps: ["jspb", "gwvz"] },
  { id: "mbts", val: 19 },
  { id: "jgnc", val: 3 },
  { id: "vwbg", val: "jtsg + mmvm", deps: ["jtsg", "mmvm"] },
  { id: "jsvg", val: "jhlq * tpgj", deps: ["jhlq", "tpgj"] },
  { id: "rjvj", val: "tcpc + lzvr", deps: ["tcpc", "lzvr"] },
  { id: "cnmf", val: "qtbz + bphw", deps: ["qtbz", "bphw"] },
  { id: "ddjr", val: 3 },
  { id: "wtph", val: 10 },
  { id: "dbvl", val: 9 },
  { id: "mznq", val: "gvjr * fvsd", deps: ["gvjr", "fvsd"] },
  { id: "ttqj", val: "lbgr * vvvt", deps: ["lbgr", "vvvt"] },
  { id: "pmjm", val: "pfqv + gcql", deps: ["pfqv", "gcql"] },
  { id: "mmbf", val: "mbhn * qczz", deps: ["mbhn", "qczz"] },
  { id: "flrz", val: "hpqt / lmjc", deps: ["hpqt", "lmjc"] },
  { id: "bgjq", val: "pwqg + gztl", deps: ["pwqg", "gztl"] },
  { id: "lggf", val: "hdmr * rqch", deps: ["hdmr", "rqch"] },
  { id: "lcht", val: "rflv / hzdv", deps: ["rflv", "hzdv"] },
  { id: "sqbf", val: 8 },
  { id: "dltm", val: 2 },
  { id: "pppg", val: 1 },
  { id: "llqr", val: 8 },
  { id: "qcbr", val: 3 },
  { id: "ghlv", val: 3 },
  { id: "grrs", val: 7 },
  { id: "hzdv", val: 2 },
  { id: "zbvf", val: "rpgl + cnlj", deps: ["rpgl", "cnlj"] },
  { id: "mphw", val: 3 },
  { id: "ptbf", val: 2 },
  { id: "jvjt", val: "hrpv / tvcv", deps: ["hrpv", "tvcv"] },
  { id: "pthv", val: 2 },
  { id: "grtd", val: "gfwt * lszf", deps: ["gfwt", "lszf"] },
  { id: "mfmc", val: "shjp + pthm", deps: ["shjp", "pthm"] },
  { id: "qrnh", val: 14 },
  { id: "bbhw", val: "ldjj + zhcs", deps: ["ldjj", "zhcs"] },
  { id: "lvwd", val: 16 },
  { id: "dpvg", val: "hzlv * ddcp", deps: ["hzlv", "ddcp"] },
  { id: "dwqs", val: 2 },
  { id: "wgfb", val: 3 },
  { id: "jtgt", val: 9 },
  { id: "ljbd", val: "bbbs + msfw", deps: ["bbbs", "msfw"] },
  { id: "rbvv", val: "ctwj + wblt", deps: ["ctwj", "wblt"] },
  { id: "dqtq", val: 3 },
  { id: "vntw", val: "jsgf + wdfz", deps: ["jsgf", "wdfz"] },
  { id: "bzlh", val: "jthg * rpdh", deps: ["jthg", "rpdh"] },
  { id: "sbnf", val: 1 },
  { id: "lcwm", val: 5 },
  { id: "pgsr", val: 2 },
  { id: "sgbm", val: "lvtf * rcdn", deps: ["lvtf", "rcdn"] },
  { id: "mssv", val: 3 },
  { id: "lnqt", val: 3 },
  { id: "srdl", val: 8 },
  { id: "wvpj", val: 11 },
  { id: "ntdq", val: "qnwn * rncs", deps: ["qnwn", "rncs"] },
  { id: "cgmp", val: "mgbt * jjrq", deps: ["mgbt", "jjrq"] },
  { id: "rfmp", val: "cgmp / svnq", deps: ["cgmp", "svnq"] },
  { id: "wtfw", val: 2 },
  { id: "wpzb", val: "snsz / lrst", deps: ["snsz", "lrst"] },
  { id: "msdv", val: 19 },
  { id: "bbbq", val: "jmsv + dwwz", deps: ["jmsv", "dwwz"] },
  { id: "prqm", val: 2 },
  { id: "jgrf", val: 5 },
  { id: "mdzg", val: "zmrw + jmfw", deps: ["zmrw", "jmfw"] },
  { id: "snsd", val: "dclf + mprj", deps: ["dclf", "mprj"] },
  { id: "ttpj", val: 2 },
  { id: "tjmj", val: "zbvf * vtzc", deps: ["zbvf", "vtzc"] },
  { id: "ljfw", val: 4 },
  { id: "vljq", val: "htmt * wjbm", deps: ["htmt", "wjbm"] },
  { id: "ngrl", val: 3 },
  { id: "lrst", val: 2 },
  { id: "ccnw", val: "wlwz + pshc", deps: ["wlwz", "pshc"] },
  { id: "hrzv", val: "cscm * nrfp", deps: ["cscm", "nrfp"] },
  { id: "gchm", val: "gzbm * bphn", deps: ["gzbm", "bphn"] },
  { id: "czbb", val: 3 },
  { id: "plgr", val: 4 },
  { id: "tscp", val: 3 },
  { id: "jmjv", val: 5 },
  { id: "czmm", val: 13 },
  { id: "cqgb", val: 20 },
  { id: "nnnp", val: "mggt + fqpj", deps: ["mggt", "fqpj"] },
  { id: "bjmz", val: "wppt + chfz", deps: ["wppt", "chfz"] },
  { id: "pfqv", val: 3 },
  { id: "zmsl", val: "zfcd - snmm", deps: ["zfcd", "snmm"] },
  { id: "tntl", val: "ctzh - nbfw", deps: ["ctzh", "nbfw"] },
  { id: "wlpd", val: 5 },
  { id: "swwq", val: 16 },
  { id: "hlnf", val: 2 },
  { id: "vpgz", val: 2 },
  { id: "pfrf", val: 3 },
  { id: "mqnh", val: "jgnc + zjvq", deps: ["jgnc", "zjvq"] },
  { id: "lclm", val: 2 },
  { id: "jsqw", val: "htqp + dhlf", deps: ["htqp", "dhlf"] },
  { id: "zhhj", val: 2 },
  { id: "szcz", val: 2 },
  { id: "wbnl", val: 3 },
  { id: "nwzw", val: "tdrn - gcdr", deps: ["tdrn", "gcdr"] },
  { id: "rjgj", val: 7 },
  { id: "rnlr", val: "vhhg / nnjp", deps: ["vhhg", "nnjp"] },
  { id: "pvpl", val: 2 },
  { id: "qlnb", val: 5 },
  { id: "btwr", val: 10 },
  { id: "vwzz", val: "mfmb + zhmm", deps: ["mfmb", "zhmm"] },
  { id: "gpbr", val: 3 },
  { id: "gpzw", val: 3 },
  { id: "dblh", val: "lwpg + smhj", deps: ["lwpg", "smhj"] },
  { id: "hbsv", val: "hdwt * rtnt", deps: ["hdwt", "rtnt"] },
  { id: "bbtz", val: "grvh + lmng", deps: ["grvh", "lmng"] },
  { id: "grvh", val: "dqhd - qmbc", deps: ["dqhd", "qmbc"] },
  { id: "lmvw", val: "gfsr + jsrt", deps: ["gfsr", "jsrt"] },
  { id: "scvc", val: 2 },
  { id: "wtjh", val: 3 },
  { id: "hpzd", val: 11 },
  { id: "nwcw", val: 4 },
  { id: "ntzl", val: "zhjd + slwq", deps: ["zhjd", "slwq"] },
  { id: "dztl", val: 17 },
  { id: "zwfh", val: "zmsb + wqsv", deps: ["zmsb", "wqsv"] },
  { id: "wpnt", val: 10 },
  { id: "grtt", val: 3 },
  { id: "rqwd", val: "dfhh - pmnj", deps: ["dfhh", "pmnj"] },
  { id: "bcdp", val: "grtd * wnbz", deps: ["grtd", "wnbz"] },
  { id: "nrpj", val: "lvrp + nhgf", deps: ["lvrp", "nhgf"] },
  { id: "jvgg", val: 2 },
  { id: "nfvl", val: "bgjq + tddb", deps: ["bgjq", "tddb"] },
  { id: "jcdg", val: "mbsr * lvwv", deps: ["mbsr", "lvwv"] },
  { id: "lnmg", val: "htrl + dtfm", deps: ["htrl", "dtfm"] },
  { id: "vfps", val: "dlsm + ntzl", deps: ["dlsm", "ntzl"] },
  { id: "bphn", val: "fscl + vcsr", deps: ["fscl", "vcsr"] },
  { id: "bjbz", val: "qdvg - tvzr", deps: ["qdvg", "tvzr"] },
  { id: "tnnd", val: 2 },
  { id: "vbgh", val: "hvzb * jcdg", deps: ["hvzb", "jcdg"] },
  { id: "snjc", val: 2 },
  { id: "dbjj", val: "nbrt * wgfb", deps: ["nbrt", "wgfb"] },
  { id: "fvjt", val: "rggc + znfp", deps: ["rggc", "znfp"] },
  { id: "ssbj", val: 2 },
  { id: "hppq", val: 10 },
  { id: "qsqc", val: "cjhm + dhrh", deps: ["cjhm", "dhrh"] },
  { id: "rtgg", val: 5 },
  { id: "nnsn", val: "npgh * srgw", deps: ["npgh", "srgw"] },
  { id: "pjgn", val: 4 },
  { id: "ldqj", val: "gsnd + zdlm", deps: ["gsnd", "zdlm"] },
  { id: "npgh", val: 3 },
  { id: "pqsg", val: 5 },
  { id: "mgjf", val: "dzcc * thjb", deps: ["dzcc", "thjb"] },
  { id: "ptzq", val: 2 },
  { id: "pjvz", val: "bzvv * sphp", deps: ["bzvv", "sphp"] },
  { id: "tpnc", val: "tgsp / rsgp", deps: ["tgsp", "rsgp"] },
  { id: "bsnf", val: "qprv + bsvn", deps: ["qprv", "bsvn"] },
  { id: "fgjn", val: "gbgr * vnct", deps: ["gbgr", "vnct"] },
  { id: "njsj", val: 2 },
  { id: "vfvv", val: 4 },
  { id: "mvtj", val: "jsdj / rmfr", deps: ["jsdj", "rmfr"] },
  { id: "lwwt", val: 7 },
  { id: "gmzd", val: "cqsz + cpwg", deps: ["cqsz", "cpwg"] },
  { id: "rsvv", val: "vzzj + qwzm", deps: ["vzzj", "qwzm"] },
  { id: "dtfm", val: 1 },
  { id: "hwpm", val: "ptvf + gglm", deps: ["ptvf", "gglm"] },
  { id: "wjcv", val: 5 },
  { id: "ptln", val: 5 },
  { id: "fqvg", val: 4 },
  { id: "dhbr", val: 13 },
  { id: "fmmr", val: "gvnm - gdrz", deps: ["gvnm", "gdrz"] },
  { id: "cfgn", val: 18 },
  { id: "brgj", val: "vlhl + hdlq", deps: ["vlhl", "hdlq"] },
  { id: "jbdz", val: "wvlm * qqnm", deps: ["wvlm", "qqnm"] },
  { id: "humn", val: 506 },
  { id: "rdlb", val: "zwjj / qmpb", deps: ["zwjj", "qmpb"] },
  { id: "tvsl", val: 1 },
  { id: "fzvr", val: 12 },
  { id: "lgpq", val: "bjml * ngrl", deps: ["bjml", "ngrl"] },
  { id: "rtgq", val: "wmhw + mcbm", deps: ["wmhw", "mcbm"] },
  { id: "ftsg", val: 3 },
  { id: "vmvg", val: 3 },
  { id: "zwnl", val: 11 },
  { id: "ffcg", val: 18 },
  { id: "llcs", val: 7 },
  { id: "mggt", val: "sbwc * srjv", deps: ["sbwc", "srjv"] },
  { id: "dgmb", val: "qprd * nncc", deps: ["qprd", "nncc"] },
  { id: "fsdv", val: "hbsv + rtpz", deps: ["hbsv", "rtpz"] },
  { id: "shjr", val: 3 },
  { id: "fgzm", val: 2 },
  { id: "pzfp", val: "ctpj * znqw", deps: ["ctpj", "znqw"] },
  { id: "zzhd", val: "ccwv + mmbf", deps: ["ccwv", "mmbf"] },
  { id: "qzjw", val: 2 },
  { id: "pzdz", val: "ngbs * drtm", deps: ["ngbs", "drtm"] },
  { id: "tpnl", val: "vwsr + tstm", deps: ["vwsr", "tstm"] },
  { id: "vsrj", val: 17 },
  { id: "vrhf", val: "vdnw + htwq", deps: ["vdnw", "htwq"] },
  { id: "scwz", val: 4 },
  { id: "tswq", val: 2 },
  { id: "lvrp", val: 4 },
  { id: "lmng", val: "fprl * ttcq", deps: ["fprl", "ttcq"] },
  { id: "cqjc", val: 2 },
  { id: "dwtn", val: 11 },
  { id: "ttdj", val: 6 },
  { id: "bnsf", val: "ctzs - drhm", deps: ["ctzs", "drhm"] },
  { id: "sfwh", val: 4 },
  { id: "zfqj", val: 10 },
  { id: "vtwp", val: 2 },
  { id: "znqw", val: 2 },
  { id: "lgqz", val: "dvnr * pvwq", deps: ["dvnr", "pvwq"] },
  { id: "jmmh", val: 2 },
  { id: "tlqv", val: "qnfv + zjwd", deps: ["qnfv", "zjwd"] },
  { id: "qvhs", val: "wdhn * rscv", deps: ["wdhn", "rscv"] },
  { id: "zhcf", val: "qvcb * sdhl", deps: ["qvcb", "sdhl"] },
  { id: "wcgt", val: "nqgv + rtbz", deps: ["nqgv", "rtbz"] },
  { id: "jcvs", val: "snsb + cvbc", deps: ["snsb", "cvbc"] },
  { id: "lfdn", val: "lgrl * qfnv", deps: ["lgrl", "qfnv"] },
  { id: "qcvs", val: 1 },
  { id: "dbww", val: 10 },
  { id: "snmm", val: 11 },
  { id: "qpwn", val: 4 },
  { id: "nzbm", val: "tmbd + nnph", deps: ["tmbd", "nnph"] },
  { id: "gprf", val: 3 },
  { id: "vcpv", val: "gvvz + wtcf", deps: ["gvvz", "wtcf"] },
  { id: "qsqv", val: "vstf + lcht", deps: ["vstf", "lcht"] },
  { id: "htqp", val: "sbmq + zcsz", deps: ["sbmq", "zcsz"] },
  { id: "jrtc", val: "qjvt + hhzn", deps: ["qjvt", "hhzn"] },
  { id: "hvrt", val: "cbbp + jhqv", deps: ["cbbp", "jhqv"] },
  { id: "pbwc", val: 1 },
  { id: "svrl", val: 3 },
  { id: "mqbj", val: 9 },
  { id: "jjzh", val: 2 },
  { id: "wlnr", val: "mnnf + zlvb", deps: ["mnnf", "zlvb"] },
  { id: "qvjv", val: "ddlw * mvvn", deps: ["ddlw", "mvvn"] },
  { id: "mblw", val: 11 },
  { id: "njqw", val: "qzjw * wwbl", deps: ["qzjw", "wwbl"] },
  { id: "dzcb", val: 2 },
  { id: "jdfl", val: 3 },
  { id: "lwpg", val: 10 },
  { id: "dhnv", val: "lvvg / rhjh", deps: ["lvvg", "rhjh"] },
  { id: "zfvl", val: 7 },
  { id: "bwws", val: "bnqm / mwjp", deps: ["bnqm", "mwjp"] },
  { id: "lvtj", val: 5 },
  { id: "dscc", val: "vwrv + nfvq", deps: ["vwrv", "nfvq"] },
  { id: "mcht", val: 2 },
  { id: "ctbt", val: 1 },
  { id: "vlmh", val: 4 },
  { id: "hvqd", val: 3 },
  { id: "psnz", val: "pjfv * zqrl", deps: ["pjfv", "zqrl"] },
  { id: "ftmv", val: 5 },
  { id: "fscl", val: "ldlr - bslz", deps: ["ldlr", "bslz"] },
  { id: "nlwj", val: 3 },
  { id: "sltr", val: 2 },
  { id: "rgjn", val: "gmgp + rtgq", deps: ["gmgp", "rtgq"] },
  { id: "jzch", val: "tgjp + mvlt", deps: ["tgjp", "mvlt"] },
  { id: "dwcq", val: "vjzp * gcpg", deps: ["vjzp", "gcpg"] },
  { id: "lsrm", val: "twtm - stpf", deps: ["twtm", "stpf"] },
  { id: "pvfw", val: "psnr * hzsn", deps: ["psnr", "hzsn"] },
  { id: "fmsj", val: 11 },
  { id: "mcvc", val: 5 },
  { id: "rtbz", val: 12 },
  { id: "lfvd", val: "hdhh * hwfz", deps: ["hdhh", "hwfz"] },
  { id: "pvwq", val: 2 },
  { id: "gwmz", val: "qfrm - pthv", deps: ["qfrm", "pthv"] },
  { id: "sdsz", val: "wcgw * wrpq", deps: ["wcgw", "wrpq"] },
  { id: "qlfp", val: "gwpt + zhqn", deps: ["gwpt", "zhqn"] },
  { id: "fswp", val: 3 },
  { id: "sgtr", val: 4 },
  { id: "rwsw", val: "lhfl * pznl", deps: ["lhfl", "pznl"] },
  { id: "wfwh", val: 4 },
  { id: "hjvn", val: "zprt * cbqv", deps: ["zprt", "cbqv"] },
  { id: "jmwr", val: 2 },
  { id: "vprl", val: 3 },
  { id: "hdwt", val: 3 },
  { id: "dqch", val: "qghq * mdzg", deps: ["qghq", "mdzg"] },
  { id: "wbvd", val: "sstt * wtph", deps: ["sstt", "wtph"] },
  { id: "vwrr", val: 7 },
  { id: "zjvq", val: "fbfc * rbmt", deps: ["fbfc", "rbmt"] },
  { id: "gltv", val: 4 },
  { id: "mzrc", val: 20 },
  { id: "psqh", val: 2 },
  { id: "zrqr", val: "trhb + sfdc", deps: ["trhb", "sfdc"] },
  { id: "zlld", val: 2 },
  { id: "lgsw", val: "jntz * rcbd", deps: ["jntz", "rcbd"] },
  { id: "fcqr", val: 2 },
  { id: "bzwt", val: 2 },
  { id: "tdpr", val: 7 },
  { id: "qwtz", val: 3 },
  { id: "dmhw", val: "qhzs + sbnf", deps: ["qhzs", "sbnf"] },
  { id: "vszn", val: 2 },
  { id: "qnpt", val: "bhrb - fngq", deps: ["bhrb", "fngq"] },
  { id: "bsgf", val: 3 },
  { id: "qzqz", val: 3 },
  { id: "jjtf", val: "ntdq - qngn", deps: ["ntdq", "qngn"] },
  { id: "jmsv", val: 3 },
  { id: "grcl", val: 3 },
  { id: "rbqg", val: 5 },
  { id: "dmvv", val: 2 },
  { id: "mjsv", val: "bbtz + gmzd", deps: ["bbtz", "gmzd"] },
  { id: "rtnt", val: "mnht + hgjg", deps: ["mnht", "hgjg"] },
  { id: "msss", val: 4 },
  { id: "wvcp", val: "jpjz * gdsn", deps: ["jpjz", "gdsn"] },
  { id: "pvgt", val: 2 },
  { id: "qnlq", val: 4 },
  { id: "fcdl", val: "zqfl / mnmq", deps: ["zqfl", "mnmq"] },
  { id: "jlvs", val: "rbfr * rwjc", deps: ["rbfr", "rwjc"] },
  { id: "smcz", val: 12 },
  { id: "fdjw", val: "bbnr * trzn", deps: ["bbnr", "trzn"] },
  { id: "qjff", val: "mdrf * tmjt", deps: ["mdrf", "tmjt"] },
  { id: "mggw", val: "lsrm / tmnv", deps: ["lsrm", "tmnv"] },
  { id: "hddg", val: 3 },
  { id: "vzff", val: "fqvg * rnrc", deps: ["fqvg", "rnrc"] },
  { id: "ntmg", val: "swwq * tzct", deps: ["swwq", "tzct"] },
  { id: "gwvz", val: 5 },
  { id: "cczz", val: "pvqf * zstp", deps: ["pvqf", "zstp"] },
  { id: "zjlz", val: 2 },
  { id: "nnjp", val: 2 },
  { id: "mbmw", val: "mpht + jvjt", deps: ["mpht", "jvjt"] },
  { id: "ndrb", val: "nwgh * fnvm", deps: ["nwgh", "fnvm"] },
  { id: "jslr", val: "vqsp / qwcv", deps: ["vqsp", "qwcv"] },
  { id: "vwrv", val: 9 },
  { id: "rvcj", val: 2 },
  { id: "mwjp", val: 2 },
  { id: "nbnw", val: 3 },
  { id: "tdfv", val: 5 },
  { id: "rhhv", val: 2 },
  { id: "fngq", val: 3 },
  { id: "bttg", val: 1 },
  { id: "cqgn", val: 17 },
  { id: "drnd", val: 18 },
  { id: "rbdq", val: "fsdv / qsll", deps: ["fsdv", "qsll"] },
  { id: "mfrp", val: "hpzd * wwqf", deps: ["hpzd", "wwqf"] },
  { id: "pwmp", val: "mbbt * tdpr", deps: ["mbbt", "tdpr"] },
  { id: "zjwd", val: 5 },
  { id: "vjzp", val: 4 },
  { id: "tstm", val: 3 },
  { id: "gzbm", val: "drnd + gsls", deps: ["drnd", "gsls"] },
  { id: "qsll", val: 6 },
  { id: "lhbt", val: "spbm * rhgg", deps: ["spbm", "rhgg"] },
  { id: "lldj", val: "dbzs * bmcv", deps: ["dbzs", "bmcv"] },
  { id: "njwt", val: "jpcj * vsrl", deps: ["jpcj", "vsrl"] },
  { id: "tbcl", val: "zjwn + cfql", deps: ["zjwn", "cfql"] },
  { id: "rlbh", val: "btwr + gtnl", deps: ["btwr", "gtnl"] },
  { id: "ncmp", val: 5 },
  { id: "prjz", val: 14 },
  { id: "qncr", val: "pfbv - sbsl", deps: ["pfbv", "sbsl"] },
  { id: "pphs", val: 3 },
  { id: "shsd", val: 7 },
  { id: "sphs", val: "cbpq * zgvq", deps: ["cbpq", "zgvq"] },
  { id: "lhcw", val: 13 },
  { id: "tjgf", val: 2 },
  { id: "rnbh", val: 5 },
  { id: "dnbn", val: "qnpt * jvdh", deps: ["qnpt", "jvdh"] },
  { id: "vlpq", val: "btfj + vbwm", deps: ["btfj", "vbwm"] },
  { id: "hjgn", val: 5 },
  { id: "qqnm", val: 2 },
  { id: "tgjh", val: "prvl + zvns", deps: ["prvl", "zvns"] },
  { id: "nntg", val: "nrls * djsf", deps: ["nrls", "djsf"] },
  { id: "swnn", val: "cqgb + hvrt", deps: ["cqgb", "hvrt"] },
  { id: "zqsl", val: "jznt * gpbz", deps: ["jznt", "gpbz"] },
  { id: "lbzq", val: "srzb * lrlr", deps: ["srzb", "lrlr"] },
  { id: "dncb", val: 7 },
  { id: "wmmh", val: 4 },
  { id: "drzm", val: 2 },
  { id: "hzvw", val: 5 },
  { id: "pzfz", val: "bbsl * dmvv", deps: ["bbsl", "dmvv"] },
  { id: "jfpm", val: "mpqf + lgsw", deps: ["mpqf", "lgsw"] },
  { id: "dfvp", val: 3 },
  { id: "jmfw", val: "gqzj - pjnv", deps: ["gqzj", "pjnv"] },
  { id: "thmh", val: 2 },
  { id: "vhql", val: 2 },
  { id: "mpqf", val: "jvvs * trtc", deps: ["jvvs", "trtc"] },
  { id: "vghd", val: "lggf / rglt", deps: ["lggf", "rglt"] },
  { id: "trfg", val: "jgqf * hlzj", deps: ["jgqf", "hlzj"] },
  { id: "pfzl", val: 2 },
  { id: "vqsp", val: "pftp * hmpj", deps: ["pftp", "hmpj"] },
  { id: "vqpp", val: 12 },
  { id: "nwgh", val: 2 },
  { id: "lrmr", val: "njqw * lzrd", deps: ["njqw", "lzrd"] },
  { id: "wdbt", val: 3 },
  { id: "bjws", val: "wqzj + vghd", deps: ["wqzj", "vghd"] },
  { id: "sjwm", val: 3 },
  { id: "rmqp", val: "qclz * hhnc", deps: ["qclz", "hhnc"] },
  { id: "gqzj", val: "vgqb + bghm", deps: ["vgqb", "bghm"] },
  { id: "dtmb", val: "jvtv * wsgm", deps: ["jvtv", "wsgm"] },
  { id: "pbds", val: 2 },
  { id: "drnq", val: 4 },
  { id: "gghq", val: "gqjl + bsnt", deps: ["gqjl", "bsnt"] },
  { id: "cscm", val: 4 },
  { id: "cftg", val: "gqll * tbgp", deps: ["gqll", "tbgp"] },
  { id: "rsrp", val: 1 },
  { id: "rhsb", val: "cbvz / ptrc", deps: ["cbvz", "ptrc"] },
  { id: "bwhf", val: 3 },
  { id: "stsz", val: "bbbq + wbtw", deps: ["bbbq", "wbtw"] },
  { id: "grrm", val: 11 },
  { id: "jjzj", val: "drfh / lqfm", deps: ["drfh", "lqfm"] },
  { id: "sbhj", val: "cwcd * gwmz", deps: ["cwcd", "gwmz"] },
  { id: "wqsv", val: 1 },
  { id: "bcjv", val: 3 },
  { id: "lbbp", val: 13 },
  { id: "nfvb", val: "dmhw * sbhv", deps: ["dmhw", "sbhv"] },
  { id: "jmvh", val: 4 },
  { id: "rtnc", val: "dscc * tgzm", deps: ["dscc", "tgzm"] },
  { id: "fflg", val: "vntw * cglj", deps: ["vntw", "cglj"] },
  { id: "szrh", val: 4 },
  { id: "jfbt", val: "cngv / ncmp", deps: ["cngv", "ncmp"] },
  { id: "gcpg", val: "mggw + fbcm", deps: ["mggw", "fbcm"] },
  { id: "qgzq", val: "ccnw * rbmh", deps: ["ccnw", "rbmh"] },
  { id: "ggcc", val: "lldj - ttdj", deps: ["lldj", "ttdj"] },
  { id: "ndgd", val: 5 },
  { id: "gzzt", val: "zfwt + ggwm", deps: ["zfwt", "ggwm"] },
  { id: "vvfh", val: 5 },
  { id: "rgbg", val: 2 },
  { id: "jzsr", val: "slhw * shjr", deps: ["slhw", "shjr"] },
  { id: "ltcv", val: 10 },
  { id: "fhcc", val: "hhvl * tfqh", deps: ["hhvl", "tfqh"] },
  { id: "cqdt", val: 2 },
  { id: "sfhv", val: "dgmp / jgrf", deps: ["dgmp", "jgrf"] },
  { id: "vztr", val: "zzts + ggjs", deps: ["zzts", "ggjs"] },
  { id: "zfqd", val: "jcgq + qwgs", deps: ["jcgq", "qwgs"] },
  { id: "mnmq", val: 2 },
  { id: "zpnh", val: "mqww / gjmc", deps: ["mqww", "gjmc"] },
  { id: "cpwg", val: 1 },
  { id: "tqnd", val: "vlmh * vctt", deps: ["vlmh", "vctt"] },
  { id: "nnjl", val: "lrbl * vwbg", deps: ["lrbl", "vwbg"] },
  { id: "sphp", val: 13 },
  { id: "lgrn", val: "dbtp + rdlb", deps: ["dbtp", "rdlb"] },
  { id: "dsrz", val: 5 },
  { id: "cssq", val: "clzl + cphw", deps: ["clzl", "cphw"] },
  { id: "lcrh", val: "qwtz * fpwp", deps: ["qwtz", "fpwp"] },
  { id: "pmjc", val: 2 },
  { id: "cbcb", val: "zjzn * wtth", deps: ["zjzn", "wtth"] },
  { id: "lmfg", val: "ltcv - mphw", deps: ["ltcv", "mphw"] },
  { id: "dhdz", val: 2 },
  { id: "ntcg", val: 14 },
  { id: "vmhv", val: "dtrm * sshd", deps: ["dtrm", "sshd"] },
  { id: "jgjs", val: 4 },
  { id: "czjm", val: "qvhs + dthh", deps: ["qvhs", "dthh"] },
  { id: "cnnj", val: 3 },
  { id: "bsbq", val: "jtfl * qtbt", deps: ["jtfl", "qtbt"] },
  { id: "wslv", val: "jsqw + bpzq", deps: ["jsqw", "bpzq"] },
  { id: "dqdc", val: 4 },
  { id: "ffwg", val: 3 },
  { id: "zvns", val: "ghzj * nwbb", deps: ["ghzj", "nwbb"] },
  { id: "nqzm", val: "prqm * zlsl", deps: ["prqm", "zlsl"] },
  { id: "cvgg", val: 4 },
  { id: "flvc", val: 13 },
  { id: "rpvn", val: 2 },
  { id: "dghh", val: "dzhn + gjpg", deps: ["dzhn", "gjpg"] },
  { id: "dlbp", val: 3 },
  { id: "hzsn", val: 3 },
  { id: "rrbw", val: "mwnr + zfnb", deps: ["mwnr", "zfnb"] },
  { id: "rcdn", val: 3 },
  { id: "msrb", val: 3 },
  { id: "mcds", val: 3 },
  { id: "wsrw", val: 5 },
  { id: "ldsn", val: "hwgr / gmnm", deps: ["hwgr", "gmnm"] },
  { id: "msfg", val: 15 },
  { id: "clhv", val: 2 },
  { id: "vdlm", val: 2 },
  { id: "mdmc", val: 4 },
  { id: "zhgh", val: 12 },
  { id: "sdgr", val: "tvbv * dwll", deps: ["tvbv", "dwll"] },
  { id: "fpzm", val: "zgsg + mwth", deps: ["zgsg", "mwth"] },
  { id: "phgg", val: "hvfn / lfpr", deps: ["hvfn", "lfpr"] },
  { id: "lvnw", val: "dztl - sgtr", deps: ["dztl", "sgtr"] },
  { id: "sbmq", val: "dcvj * nnmf", deps: ["dcvj", "nnmf"] },
  { id: "jnjt", val: 3 },
  { id: "vbht", val: 1 },
  { id: "htmt", val: "lmps * brfn", deps: ["lmps", "brfn"] },
  { id: "tfqh", val: "bcgf + sdsz", deps: ["bcgf", "sdsz"] },
  { id: "vhvt", val: 5 },
  { id: "cdrv", val: "jwqc * dscp", deps: ["jwqc", "dscp"] },
  { id: "ggjs", val: 4 },
  { id: "bbzs", val: 4 },
  { id: "vsht", val: 4 },
  { id: "fhhc", val: 7 },
  { id: "dbqw", val: 2 },
  { id: "clsd", val: 2 },
  { id: "vsdd", val: "ptlt * pgsr", deps: ["ptlt", "pgsr"] },
  { id: "dhdh", val: "mfnj + tzbj", deps: ["mfnj", "tzbj"] },
  { id: "nfvf", val: 11 },
  { id: "jflt", val: 4 },
  { id: "zwgd", val: 1 },
  { id: "btfc", val: 2 },
  { id: "hjzt", val: "lwpr + hrtd", deps: ["lwpr", "hrtd"] },
  { id: "dpsb", val: "dbjj * vpqv", deps: ["dbjj", "vpqv"] },
  { id: "jthg", val: "fswp * slnn", deps: ["fswp", "slnn"] },
  { id: "bmqg", val: 1 },
  { id: "qqnw", val: 2 },
  { id: "vrjw", val: "msrb * dpzs", deps: ["msrb", "dpzs"] },
  { id: "mjvp", val: 3 },
  { id: "sdws", val: "sbbc * vhmq", deps: ["sbbc", "vhmq"] },
  { id: "qvjr", val: "wmhm * vsdd", deps: ["wmhm", "vsdd"] },
  { id: "pzfv", val: 2 },
  { id: "ctzl", val: 4 },
  { id: "jshj", val: 3 },
  { id: "vwmg", val: 3 },
  { id: "dtff", val: "fnwh + hrvc", deps: ["fnwh", "hrvc"] },
  { id: "qjvt", val: 8 },
  { id: "rlgr", val: 2 },
  { id: "pspg", val: 2 },
  { id: "ngrv", val: 2 },
  { id: "gwpt", val: 13 },
  { id: "lvms", val: "fhht * vzwg", deps: ["fhht", "vzwg"] },
  { id: "prfd", val: 2 },
  { id: "qrqp", val: 2 },
  { id: "dcvj", val: 3 },
  { id: "zttr", val: "pswb * ghjv", deps: ["pswb", "ghjv"] },
  { id: "stpf", val: "wndc + bnbb", deps: ["wndc", "bnbb"] },
  { id: "wgpv", val: "sntv + wcch", deps: ["sntv", "wcch"] },
  { id: "fggn", val: "pbqf * jtpd", deps: ["pbqf", "jtpd"] },
  { id: "jbld", val: "rwmr + hgpp", deps: ["rwmr", "hgpp"] },
  { id: "vbvd", val: 3 },
  { id: "qjst", val: "spzc * frpb", deps: ["spzc", "frpb"] },
  { id: "wdhn", val: 13 },
  { id: "gdsn", val: "llgt + pjgn", deps: ["llgt", "pjgn"] },
  { id: "zscv", val: "wlbz + lbjg", deps: ["wlbz", "lbjg"] },
  { id: "nlhd", val: "qlgj * lscb", deps: ["qlgj", "lscb"] },
  { id: "fvcc", val: 5 },
  { id: "nhpl", val: 2 },
  { id: "mtwz", val: 2 },
  { id: "wlwz", val: "vgnr + pphs", deps: ["vgnr", "pphs"] },
  { id: "mptb", val: 3 },
  { id: "bnbb", val: "fcqr * clgw", deps: ["fcqr", "clgw"] },
  { id: "vsgr", val: 6 },
  { id: "nqfb", val: "ljbd / rlgr", deps: ["ljbd", "rlgr"] },
  { id: "nrls", val: 5 },
  { id: "dvnr", val: 9 },
  { id: "lpqg", val: "gzbq * qmhm", deps: ["gzbq", "qmhm"] },
  { id: "bphw", val: "lghp * bwqn", deps: ["lghp", "bwqn"] },
  { id: "qdpf", val: 3 },
  { id: "spzc", val: 3 },
  { id: "mbsr", val: 3 },
  { id: "rtfg", val: 2 },
  { id: "fmzc", val: 2 },
  { id: "fprq", val: "cppq * tqfv", deps: ["cppq", "tqfv"] },
  { id: "jmrr", val: 17 },
  { id: "cnfb", val: 3 },
  { id: "cgwd", val: 5 },
  { id: "qfnt", val: "qcdv + jcvg", deps: ["qcdv", "jcvg"] },
  { id: "rnlz", val: 2 },
  { id: "zhlb", val: "dbvl + rpvn", deps: ["dbvl", "rpvn"] },
  { id: "ltbn", val: 2 },
  { id: "wdfw", val: 6 },
  { id: "lscb", val: "nwfv - vhth", deps: ["nwfv", "vhth"] },
  { id: "jgqf", val: "tpnc - lrmr", deps: ["tpnc", "lrmr"] },
  { id: "rjtc", val: 2 },
  { id: "chch", val: 5 },
  { id: "wppt", val: 2 },
  { id: "vvjq", val: "mvnf + ngft", deps: ["mvnf", "ngft"] },
  { id: "rvtp", val: "shzg + jwpt", deps: ["shzg", "jwpt"] },
  { id: "tllz", val: "vsht * ptln", deps: ["vsht", "ptln"] },
  { id: "gpbz", val: "fcrn * bzwt", deps: ["fcrn", "bzwt"] },
  { id: "jbfm", val: "rqwd * rpfz", deps: ["rqwd", "rpfz"] },
  { id: "ttgb", val: 2 },
  { id: "hbsz", val: "cqgn * ncgl", deps: ["cqgn", "ncgl"] },
  { id: "tmbd", val: 7 },
  { id: "tbrn", val: "tqcw - tvsl", deps: ["tqcw", "tvsl"] },
  { id: "jwvl", val: 2 },
  { id: "cczr", val: 2 },
  { id: "fvhn", val: 3 },
  { id: "dhrh", val: "fmbj + llpr", deps: ["fmbj", "llpr"] },
  { id: "vzww", val: "szbq * qrgz", deps: ["szbq", "qrgz"] },
  { id: "zbzd", val: 8 },
  { id: "qrtn", val: 4 },
  { id: "vsdc", val: 5 },
  { id: "dscp", val: 5 },
  { id: "qwcv", val: 2 },
  { id: "sbpw", val: "tshf * ngwz", deps: ["tshf", "ngwz"] },
  { id: "gmgz", val: 4 },
  { id: "qgmm", val: "prvh + msfv", deps: ["prvh", "msfv"] },
  { id: "cbbp", val: 1 },
  { id: "hpqt", val: "mflh + hbsq", deps: ["mflh", "hbsq"] },
  { id: "vsbd", val: 11 },
  { id: "wzth", val: "hrmp * hfps", deps: ["hrmp", "hfps"] },
  { id: "wtth", val: "twml / tzrh", deps: ["twml", "tzrh"] },
  { id: "pqwr", val: 2 },
  { id: "lqml", val: 3 },
  { id: "nhcj", val: 15 },
  { id: "hhpz", val: "rvcj * qsqc", deps: ["rvcj", "qsqc"] },
  { id: "bnhp", val: "ltrn * nqhs", deps: ["ltrn", "nqhs"] },
  { id: "pczl", val: "qwmb + zpnh", deps: ["qwmb", "zpnh"] },
  { id: "zwgg", val: "ptbf * jhls", deps: ["ptbf", "jhls"] },
  { id: "jbjz", val: 17 },
  { id: "svsh", val: "npvf + rsrp", deps: ["npvf", "rsrp"] },
  { id: "plvb", val: 5 },
  { id: "lbcq", val: "zsrg + vnzs", deps: ["zsrg", "vnzs"] },
  { id: "vbwm", val: "bsbq * mdmc", deps: ["bsbq", "mdmc"] },
  { id: "hrtd", val: 5 },
  { id: "wbgg", val: 3 },
  { id: "cbpq", val: 7 },
  { id: "chfz", val: 5 },
  { id: "lmps", val: "qbcz / rjtc", deps: ["qbcz", "rjtc"] },
  { id: "rspn", val: 14 },
  { id: "zjbp", val: 3 },
  { id: "rzfm", val: "mgsg * ctzl", deps: ["mgsg", "ctzl"] },
  { id: "mflh", val: "nlwj * qsqv", deps: ["nlwj", "qsqv"] },
  { id: "cnvz", val: "dzvc * svrl", deps: ["dzvc", "svrl"] },
  { id: "vstf", val: 5 },
  { id: "mnsw", val: 4 },
  { id: "htrl", val: 5 },
  { id: "vnwg", val: "wqwf * rmhg", deps: ["wqwf", "rmhg"] },
  { id: "cdwj", val: "njjm - nshc", deps: ["njjm", "nshc"] },
  { id: "tptz", val: "smcc + wtnb", deps: ["smcc", "wtnb"] },
  { id: "jjrq", val: "zmvp + fvmb", deps: ["zmvp", "fvmb"] },
  { id: "qnjz", val: "trfg - bqft", deps: ["trfg", "bqft"] },
  { id: "tgzm", val: 2 },
  { id: "tngv", val: "lmlf * svfq", deps: ["lmlf", "svfq"] },
  { id: "zshl", val: 3 },
  { id: "bmfb", val: "vbvl * snjc", deps: ["vbvl", "snjc"] },
  { id: "dnzp", val: "zrdh * chch", deps: ["zrdh", "chch"] },
  { id: "zqnb", val: "fwrb + pztz", deps: ["fwrb", "pztz"] },
  { id: "hlgn", val: "lntm * zwnl", deps: ["lntm", "zwnl"] },
  { id: "rnrc", val: "fwls * qsdd", deps: ["fwls", "qsdd"] },
  { id: "tddt", val: "zhlb * hdtb", deps: ["zhlb", "hdtb"] },
  { id: "pgcd", val: "hjln + nrnw", deps: ["hjln", "nrnw"] },
  { id: "vnzs", val: "zqjb * wjvb", deps: ["zqjb", "wjvb"] },
  { id: "dqtb", val: 2 },
  { id: "bvmt", val: "vvfh * vbbd", deps: ["vvfh", "vbbd"] },
  { id: "zhjd", val: 16 },
  { id: "wtrr", val: "qhgm * qpsr", deps: ["qhgm", "qpsr"] },
  { id: "zqfl", val: "fnjg * rnlz", deps: ["fnjg", "rnlz"] },
  { id: "clcj", val: "qnfh * zcbf", deps: ["qnfh", "zcbf"] },
  { id: "jcvq", val: "dhbr * cjrn", deps: ["dhbr", "cjrn"] },
  { id: "gmcq", val: "fpzs * dtrv", deps: ["fpzs", "dtrv"] },
  { id: "fcrn", val: "slfn + hhqj", deps: ["slfn", "hhqj"] },
  { id: "fmnq", val: 3 },
  { id: "jjwn", val: "nntg * vgqr", deps: ["nntg", "vgqr"] },
  { id: "qrnp", val: 2 },
  { id: "zhmm", val: "ffcf + wmzv", deps: ["ffcf", "wmzv"] },
  { id: "ncrg", val: "nllm + lclf", deps: ["nllm", "lclf"] },
  { id: "tzwn", val: 2 },
  { id: "rbfr", val: "lggv + qfjp", deps: ["lggv", "qfjp"] },
  { id: "bbbg", val: 5 },
  { id: "qsbs", val: "lwpd + csqd", deps: ["lwpd", "csqd"] },
  { id: "frvm", val: "tbwl * tjgf", deps: ["tbwl", "tjgf"] },
  { id: "ttfq", val: "gwwd * mtwz", deps: ["gwwd", "mtwz"] },
  { id: "zprt", val: "zwmc + fvcw", deps: ["zwmc", "fvcw"] },
  { id: "btqf", val: 7 },
  { id: "dpph", val: 2 },
  { id: "lzrd", val: "pswm + jflt", deps: ["pswm", "jflt"] },
  { id: "pvmm", val: "sfwn + lcvr", deps: ["sfwn", "lcvr"] },
  { id: "qwjb", val: 5 },
  { id: "bwqn", val: 2 },
  { id: "jsng", val: 2 },
  { id: "vdnj", val: 13 },
  { id: "vcsr", val: "wgfv / pjnz", deps: ["wgfv", "pjnz"] },
  { id: "bcgf", val: "ppvn / hrlf", deps: ["ppvn", "hrlf"] },
  { id: "sqvg", val: 2 },
  { id: "rcsw", val: 3 },
  { id: "hvcd", val: 3 },
  { id: "ddcp", val: 13 },
  { id: "cqpr", val: "jtnp * ffdw", deps: ["jtnp", "ffdw"] },
  { id: "zqjb", val: 7 },
  { id: "zpmc", val: 4 },
  { id: "qzts", val: "tdgj * jmrr", deps: ["tdgj", "jmrr"] },
  { id: "mcbm", val: "lwgt + nzbm", deps: ["lwgt", "nzbm"] },
  { id: "mdws", val: 2 },
  { id: "vtzc", val: 2 },
  { id: "vmbv", val: 1 },
  { id: "bfcp", val: "ncjq * tdqd", deps: ["ncjq", "tdqd"] },
  { id: "fqpj", val: "tdhn * czmm", deps: ["tdhn", "czmm"] },
  { id: "wqcc", val: 5 },
  { id: "nmpn", val: "fgmj + hhdd", deps: ["fgmj", "hhdd"] },
  { id: "lclf", val: "wcdm * bwrs", deps: ["wcdm", "bwrs"] },
  { id: "gnlw", val: 5 },
  { id: "wzgw", val: "rmjs - dcws", deps: ["rmjs", "dcws"] },
  { id: "cdtn", val: "wjgv * tmvd", deps: ["wjgv", "tmvd"] },
  { id: "gmvr", val: "lltd + qnlq", deps: ["lltd", "qnlq"] },
  { id: "qdvg", val: "dpsb + cgpw", deps: ["dpsb", "cgpw"] },
  { id: "tgjp", val: "mhrp * sbpw", deps: ["mhrp", "sbpw"] },
  { id: "cjrn", val: 2 },
  { id: "bbnd", val: 11 },
  { id: "jqtn", val: "vzww + fcdl", deps: ["vzww", "fcdl"] },
  { id: "ppvn", val: "qmlw * strm", deps: ["qmlw", "strm"] },
  { id: "cbhg", val: 3 },
  { id: "cpwd", val: "wlnr * qddv", deps: ["wlnr", "qddv"] },
  { id: "nvzr", val: 9 },
  { id: "lgrl", val: 2 },
  { id: "ngpl", val: 2 },
  { id: "wtnb", val: "smcs * hscp", deps: ["smcs", "hscp"] },
  { id: "pftp", val: "tzrv * qdpr", deps: ["tzrv", "qdpr"] },
  { id: "hgrw", val: 6 },
  { id: "qtbz", val: "nzlp * rgbg", deps: ["nzlp", "rgbg"] },
  { id: "fvnp", val: "fggn + hrtg", deps: ["fggn", "hrtg"] },
  { id: "sfsg", val: 5 },
  { id: "gfpf", val: 2 },
  { id: "zmhl", val: 7 },
  { id: "ncjw", val: 4 },
  { id: "bwrs", val: 13 },
  { id: "cbdq", val: "tdvn + rpcd", deps: ["tdvn", "rpcd"] },
  { id: "chpt", val: 14 },
  { id: "zjwn", val: "ttwj + hmgr", deps: ["ttwj", "hmgr"] },
  { id: "pznl", val: "tmnq * glsv", deps: ["tmnq", "glsv"] },
  { id: "gfzd", val: "dnbn * mhjm", deps: ["dnbn", "mhjm"] },
  { id: "zstp", val: 3 },
  { id: "qczz", val: 5 },
  { id: "rpdh", val: "phgg + dgmb", deps: ["phgg", "dgmb"] },
  { id: "fvsd", val: "jbfm - pjvt", deps: ["jbfm", "pjvt"] },
  { id: "rmjs", val: 14 },
  { id: "jhlq", val: "dvhf * mgwl", deps: ["dvhf", "mgwl"] },
  { id: "wmcv", val: "nbfb * wcct", deps: ["nbfb", "wcct"] },
  { id: "jtpd", val: 6 },
  { id: "zgqq", val: "lbzq + szdh", deps: ["lbzq", "szdh"] },
  { id: "shjp", val: "hjss + bshn", deps: ["hjss", "bshn"] },
  { id: "dzjj", val: "wdlv + snsd", deps: ["wdlv", "snsd"] },
  { id: "vnct", val: "vsdc + tjmj", deps: ["vsdc", "tjmj"] },
  { id: "blph", val: 2 },
  { id: "vpnb", val: "grdl * nfvf", deps: ["grdl", "nfvf"] },
  { id: "tqfv", val: 5 },
  { id: "ffcf", val: 2 },
  { id: "slfn", val: 15 },
  { id: "qhjs", val: 2 },
  { id: "mpfr", val: 3 },
  { id: "swcb", val: 2 },
  { id: "nzlp", val: "mptb * pvpl", deps: ["mptb", "pvpl"] },
  { id: "mjhn", val: 3 },
  { id: "csmv", val: "llqr + hdvg", deps: ["llqr", "hdvg"] },
  { id: "bcjg", val: "shhf + ptzq", deps: ["shhf", "ptzq"] },
  { id: "fszl", val: 5 },
  { id: "mbbj", val: "gbzj - cnnj", deps: ["gbzj", "cnnj"] },
  { id: "qfjp", val: "pvpp + jsvg", deps: ["pvpp", "jsvg"] },
  { id: "vjdt", val: 17 },
  { id: "lwpd", val: "rpfl * pzsl", deps: ["rpfl", "pzsl"] },
  { id: "zndn", val: 5 },
  { id: "cgtn", val: 2 },
  { id: "hdtb", val: "lvzj - jsdl", deps: ["lvzj", "jsdl"] },
  { id: "clns", val: 13 },
  { id: "gvlj", val: "qmrn * dbqw", deps: ["qmrn", "dbqw"] },
  { id: "ggdl", val: 11 },
  { id: "snsz", val: "ffmz + dzjj", deps: ["ffmz", "dzjj"] },
  { id: "fztp", val: "lzch + ftzh", deps: ["lzch", "ftzh"] },
  { id: "crsd", val: "zzhw * vfcd", deps: ["zzhw", "vfcd"] },
  { id: "pbpl", val: "cqzw * lfbq", deps: ["cqzw", "lfbq"] },
  { id: "crmt", val: "grrs * bvrz", deps: ["grrs", "bvrz"] },
  { id: "cwcp", val: 4 },
  { id: "qffl", val: 5 },
  { id: "mdhd", val: 5 },
  { id: "mprj", val: 1 },
  { id: "nfvq", val: "mtsn * mcht", deps: ["mtsn", "mcht"] },
  { id: "bndf", val: "wppg * thbm", deps: ["wppg", "thbm"] },
  { id: "wmhm", val: 6 },
  { id: "fcgc", val: 2 },
  { id: "hvzb", val: 2 },
  { id: "bzgn", val: "qdpf * tdsd", deps: ["qdpf", "tdsd"] },
  { id: "szbq", val: 2 },
  { id: "plpv", val: "wfgp + gcsv", deps: ["wfgp", "gcsv"] },
  { id: "rjhn", val: "dlrn / zlld", deps: ["dlrn", "zlld"] },
  { id: "sfwn", val: "llsf * pclf", deps: ["llsf", "pclf"] },
  { id: "vsct", val: 3 },
  { id: "dbtp", val: "ncqw + mplh", deps: ["ncqw", "mplh"] },
  { id: "vfhb", val: "pspg * qcbr", deps: ["pspg", "qcbr"] },
  { id: "npwm", val: "fmgp + rbqg", deps: ["fmgp", "rbqg"] },
  { id: "stmg", val: 4 },
  { id: "lsfh", val: "wznd + dqch", deps: ["wznd", "dqch"] },
  { id: "cphw", val: 1 },
  { id: "jmzj", val: 3 },
  { id: "sbrz", val: "mwgg * ttgb", deps: ["mwgg", "ttgb"] },
  { id: "wdlv", val: "cqwt + qmnw", deps: ["cqwt", "qmnw"] },
  { id: "vbbd", val: 3 },
  { id: "dqbf", val: 3 },
  { id: "mzvj", val: "rcql + jsqj", deps: ["rcql", "jsqj"] },
  { id: "drhf", val: 3 },
  { id: "nzjs", val: 1 },
  { id: "lqpq", val: "frgw / njsj", deps: ["frgw", "njsj"] },
  { id: "mmlc", val: "jslr + jfjl", deps: ["jslr", "jfjl"] },
  { id: "fswt", val: 3 },
  { id: "hncs", val: "nhjj * jnjt", deps: ["nhjj", "jnjt"] },
  { id: "wbfv", val: 2 },
  { id: "mdsf", val: 3 },
  { id: "jhgd", val: 10 },
  { id: "zcwt", val: "ghzf / szrh", deps: ["ghzf", "szrh"] },
  { id: "qprv", val: "njhc + pqvt", deps: ["njhc", "pqvt"] },
  { id: "qgnb", val: 2 },
  { id: "mdrf", val: 4 },
  { id: "lfzj", val: "zqzf * vbjg", deps: ["zqzf", "vbjg"] },
  { id: "lhlp", val: "mrwt * dzfp", deps: ["mrwt", "dzfp"] },
  { id: "jhzm", val: 4 },
  { id: "mpvq", val: 12 },
  { id: "lssm", val: "grwc + ncrg", deps: ["grwc", "ncrg"] },
  { id: "fpjv", val: "vjdt * wttd", deps: ["vjdt", "wttd"] },
  { id: "lbgr", val: "lfvd + zcvd", deps: ["lfvd", "zcvd"] },
  { id: "pttb", val: "dwqs + spjg", deps: ["dwqs", "spjg"] },
  { id: "pswm", val: "lnmg + nvdr", deps: ["lnmg", "nvdr"] },
  { id: "qwqj", val: "nqzm * bzlh", deps: ["nqzm", "bzlh"] },
  { id: "ttcq", val: 3 },
  { id: "qtbt", val: 3 },
  { id: "ngwz", val: 2 },
  { id: "grdl", val: "swnn + vrtr", deps: ["swnn", "vrtr"] },
  { id: "lfbq", val: "gwhv - dtmb", deps: ["gwhv", "dtmb"] },
  { id: "nqgv", val: "fczg + htzz", deps: ["fczg", "htzz"] },
  { id: "dzcc", val: 2 },
  { id: "rhjh", val: 6 },
  { id: "vmsh", val: 3 },
  { id: "jfjl", val: "shdg + mhzn", deps: ["shdg", "mhzn"] },
  { id: "csnh", val: 4 },
  { id: "fsnw", val: 9 },
  { id: "tdrn", val: "cwdc * vmhv", deps: ["cwdc", "vmhv"] },
  { id: "gvhg", val: 2 },
  { id: "fdsc", val: 2 },
  { id: "tzrh", val: 3 },
  { id: "hmpj", val: 5 },
  { id: "fczs", val: "plvb * cbzd", deps: ["plvb", "cbzd"] },
  { id: "mbhn", val: 5 },
  { id: "fczg", val: 5 },
  { id: "qnwn", val: 2 },
  { id: "ccsm", val: "sfpq - vtsh", deps: ["sfpq", "vtsh"] },
  { id: "pclf", val: 5 },
  { id: "qhgm", val: 4 },
  { id: "rpfl", val: "gfzd + nvmd", deps: ["gfzd", "nvmd"] },
  { id: "zlpd", val: 4 },
  { id: "gwww", val: 4 },
  { id: "hfps", val: 2 },
  { id: "fwnw", val: 3 },
  { id: "njzn", val: "rwgc + zsmj", deps: ["rwgc", "zsmj"] },
  { id: "qgvj", val: "gmvr + frhv", deps: ["gmvr", "frhv"] },
  { id: "cnhr", val: 2 },
  { id: "mrzs", val: "lwwt * dvdq", deps: ["lwwt", "dvdq"] },
  { id: "llhw", val: "qddm * ctgp", deps: ["qddm", "ctgp"] },
  { id: "cmwr", val: "tfnc + ntmg", deps: ["tfnc", "ntmg"] },
  { id: "zcfn", val: 3 },
  { id: "ngzh", val: 5 },
  { id: "sfdc", val: "hfjg * plpv", deps: ["hfjg", "plpv"] },
  { id: "sdhl", val: "fgjn + bzgn", deps: ["fgjn", "bzgn"] },
  { id: "gglp", val: "chcj + mvtj", deps: ["chcj", "mvtj"] },
  { id: "fhpl", val: 7 },
  { id: "smpz", val: "qchw / jdbn", deps: ["qchw", "jdbn"] },
  { id: "nrdl", val: "dwcz + gvhg", deps: ["dwcz", "gvhg"] },
  { id: "nbfb", val: 4 },
  { id: "hbpp", val: 4 },
  { id: "gphl", val: "fspc + tllz", deps: ["fspc", "tllz"] },
  { id: "lzvr", val: "tddt * rwph", deps: ["tddt", "rwph"] },
  { id: "gmgw", val: 6 },
  { id: "nllm", val: "rprq + mrgn", deps: ["rprq", "mrgn"] },
  { id: "ltgp", val: 2 },
  { id: "nbfw", val: 2 },
  { id: "vddr", val: 2 },
  { id: "gglm", val: "bwdw + mbmw", deps: ["bwdw", "mbmw"] },
  { id: "zqfz", val: 2 },
  { id: "sshj", val: 3 },
  { id: "hwsd", val: 2 },
  { id: "ptlt", val: 3 },
  { id: "vsrl", val: "hvcz * pgcd", deps: ["hvcz", "pgcd"] },
  { id: "prvh", val: "wbdz * blgt", deps: ["wbdz", "blgt"] },
  { id: "lvwz", val: "njzn * hltf", deps: ["njzn", "hltf"] },
  { id: "lvhw", val: 9 },
  { id: "dhlf", val: 3 },
  { id: "lttp", val: 19 },
  { id: "gjpg", val: 2 },
  { id: "jsgf", val: "sbrz + gmcq", deps: ["sbrz", "gmcq"] },
  { id: "blqj", val: "mfmc / fszl", deps: ["mfmc", "fszl"] },
  { id: "qbcz", val: "ttqj + hmgw", deps: ["ttqj", "hmgw"] },
  { id: "bwdw", val: "wdnz * gqbb", deps: ["wdnz", "gqbb"] },
  { id: "ncqw", val: "fzzt + tfhb", deps: ["fzzt", "tfhb"] },
  { id: "nslg", val: "bbhw + jdph", deps: ["bbhw", "jdph"] },
  { id: "gfwt", val: "vzzm + sgbm", deps: ["vzzm", "sgbm"] },
  { id: "gmnm", val: 2 },
  { id: "wcdm", val: "gnlw * dsrz", deps: ["gnlw", "dsrz"] },
  { id: "chcj", val: 10 },
  { id: "fwfn", val: "hppl + pwjf", deps: ["hppl", "pwjf"] },
  { id: "qngn", val: "vwmg * zjpj", deps: ["vwmg", "zjpj"] },
  { id: "jdcr", val: "qblq + jshf", deps: ["qblq", "jshf"] },
  { id: "nwpf", val: "mqvs * bbnd", deps: ["mqvs", "bbnd"] },
  { id: "dhzf", val: "nlfv + hvqs", deps: ["nlfv", "hvqs"] },
  { id: "hczz", val: 2 },
  { id: "dvdm", val: 2 },
  { id: "lqfm", val: 3 },
  { id: "jtfl", val: 3 },
  { id: "vvvt", val: 2 },
  { id: "cppq", val: "vtgn * pmjc", deps: ["vtgn", "pmjc"] },
  { id: "mscr", val: 4 },
  { id: "qmjs", val: "jrtc * csmc", deps: ["jrtc", "csmc"] },
  { id: "zqrl", val: "lvwz - srls", deps: ["lvwz", "srls"] },
  { id: "wfdj", val: "rjhn * qzvb", deps: ["rjhn", "qzvb"] },
  { id: "wdgw", val: 2 },
  { id: "fdjb", val: 8 },
  { id: "mtsn", val: "fdsc * mcvc", deps: ["fdsc", "mcvc"] },
  { id: "jddm", val: "qrnp * lhnj", deps: ["qrnp", "lhnj"] },
  { id: "nzfv", val: "czwb + qvcm", deps: ["czwb", "qvcm"] },
  { id: "tzps", val: "lsdf + jsbd", deps: ["lsdf", "jsbd"] },
  { id: "jjmp", val: 2 },
  { id: "llsf", val: 18 },
  { id: "lsdf", val: 11 },
  { id: "tfmf", val: 2 },
  { id: "pthm", val: "qrtn * jzdb", deps: ["qrtn", "jzdb"] },
  { id: "jwpt", val: "lpqg / ttpj", deps: ["lpqg", "ttpj"] },
  { id: "rtph", val: "mfdm + cmjj", deps: ["mfdm", "cmjj"] },
  { id: "hhqj", val: 5 },
  { id: "nhhl", val: 4 },
  { id: "rmfr", val: 2 },
  { id: "wnhd", val: 2 },
  { id: "shdg", val: "vbgh * dqtb", deps: ["vbgh", "dqtb"] },
  { id: "mhrp", val: 3 },
  { id: "jvdh", val: "rtgg + scgl", deps: ["rtgg", "scgl"] },
  { id: "wdfz", val: "lfbv / pqwr", deps: ["lfbv", "pqwr"] },
  { id: "fswd", val: "hsfg * fswt", deps: ["hsfg", "fswt"] },
  { id: "hhjc", val: "vqpp * vrbm", deps: ["vqpp", "vrbm"] },
  { id: "frhv", val: 1 },
  { id: "sntv", val: 2 },
  { id: "hltf", val: "jdqr * zdrm", deps: ["jdqr", "zdrm"] },
  { id: "ghzj", val: "gchm - rmhr", deps: ["gchm", "rmhr"] },
  { id: "tmnq", val: 8 },
  { id: "bmdf", val: "vvjq * bsdt", deps: ["vvjq", "bsdt"] },
  { id: "fnlz", val: "gfpf * nbnw", deps: ["gfpf", "nbnw"] },
  { id: "tmjt", val: 2 },
  { id: "pmnp", val: 2 },
  { id: "jpjz", val: 2 },
  { id: "qjng", val: "dglb - dpph", deps: ["dglb", "dpph"] },
  { id: "qrgz", val: 4 },
  { id: "vszs", val: "fnsw * ghlv", deps: ["fnsw", "ghlv"] },
  { id: "vqlg", val: 2 },
  { id: "jcvg", val: 7 },
  { id: "bhml", val: 3 },
  { id: "gwvh", val: 3 },
  { id: "jspb", val: "pftm + tgsl", deps: ["pftm", "tgsl"] },
  { id: "rbmt", val: 5 },
  { id: "sfqw", val: 11 },
  { id: "ctzh", val: 8 },
  { id: "nnpd", val: 2 },
  { id: "wrpq", val: "sjwm + szhq", deps: ["sjwm", "szhq"] },
  { id: "lzqq", val: "bbbg + qwhz", deps: ["bbbg", "qwhz"] },
  { id: "pbqf", val: 3 },
  { id: "jdbn", val: 2 },
  { id: "clhb", val: "nnsn * hrfz", deps: ["nnsn", "hrfz"] },
  { id: "fpwp", val: "cgwd + wssm", deps: ["cgwd", "wssm"] },
  { id: "mjzj", val: "nrdl + fdjw", deps: ["nrdl", "fdjw"] },
  { id: "flhj", val: 7 },
  { id: "hmgw", val: "bbzs * fqsp", deps: ["bbzs", "fqsp"] },
  { id: "wqwf", val: 5 },
  { id: "bzbr", val: 2 },
  { id: "pvpp", val: "tzwh * jbdz", deps: ["tzwh", "jbdz"] },
  { id: "sdrv", val: 1 },
  { id: "qhrf", val: "ffwg * lgpq", deps: ["ffwg", "lgpq"] },
  { id: "qdcp", val: "zrhp * zjbp", deps: ["zrhp", "zjbp"] },
  { id: "hdsz", val: 17 },
  { id: "mplh", val: "rwsw / mbll", deps: ["rwsw", "mbll"] },
  { id: "nwfv", val: "pfzl * jmjv", deps: ["pfzl", "jmjv"] },
  { id: "vmhg", val: "ldqj + bjws", deps: ["ldqj", "bjws"] },
  { id: "rszm", val: 2 },
  { id: "rcbd", val: 10 },
  { id: "tvzr", val: "qnbl + jhzm", deps: ["qnbl", "jhzm"] },
  { id: "slhw", val: "shbw + ntcg", deps: ["shbw", "ntcg"] },
  { id: "jcgq", val: "hbgd / djzc", deps: ["hbgd", "djzc"] },
  { id: "hrvd", val: "wjcv + nhww", deps: ["wjcv", "nhww"] },
  { id: "zgtj", val: 11 },
  { id: "sshh", val: "fzjj + wfdj", deps: ["fzjj", "wfdj"] },
  { id: "dmmp", val: 2 },
  { id: "bqft", val: "rgjn + rbdq", deps: ["rgjn", "rbdq"] },
  { id: "rjgb", val: 2 },
  { id: "rwjc", val: 3 },
  { id: "hvcz", val: 2 },
  { id: "rpcd", val: 16 },
  { id: "fzbp", val: "flwh + pczr", deps: ["flwh", "pczr"] },
  { id: "qmlw", val: 2 },
  { id: "hrvc", val: "qcvs + svjj", deps: ["qcvs", "svjj"] },
  { id: "tzrv", val: 5 },
  { id: "jtnp", val: "ffcg - vgmc", deps: ["ffcg", "vgmc"] },
  { id: "vfcd", val: "hrzv - dmsz", deps: ["hrzv", "dmsz"] },
  { id: "pvpg", val: 3 },
  { id: "jjgc", val: 2 },
  { id: "rhfq", val: 3 },
  { id: "wzdd", val: 6 },
  { id: "tpwg", val: "dmms + psdf", deps: ["dmms", "psdf"] },
  { id: "srgw", val: "fztp + jcvs", deps: ["fztp", "jcvs"] },
  { id: "wjgv", val: "msss + dqtq", deps: ["msss", "dqtq"] },
  { id: "nvjt", val: "fzbw + ctbt", deps: ["fzbw", "ctbt"] },
  { id: "wptt", val: "dblh + pzdz", deps: ["dblh", "pzdz"] },
  { id: "ctgp", val: 2 },
  { id: "lbjg", val: 12 },
  { id: "hbdn", val: "wgpv * znjw", deps: ["wgpv", "znjw"] },
  { id: "gwhv", val: "rdgm + zfml", deps: ["rdgm", "zfml"] },
  { id: "sbbc", val: "dvcf * mssv", deps: ["dvcf", "mssv"] },
  { id: "zsrg", val: "pcfg * twvq", deps: ["pcfg", "twvq"] },
  { id: "wcfb", val: 2 },
  { id: "wwzn", val: 5 },
  { id: "nhww", val: 12 },
  { id: "wtgf", val: "rrbw * qdpv", deps: ["rrbw", "qdpv"] },
  { id: "gmdn", val: "nzcj * mcwv", deps: ["nzcj", "mcwv"] },
  { id: "hdlq", val: "rqgl * zcfn", deps: ["rqgl", "zcfn"] },
  { id: "phbz", val: 2 },
  { id: "scvw", val: "zrqr - tngv", deps: ["zrqr", "tngv"] },
  { id: "cfql", val: "lmdh - rcgh", deps: ["lmdh", "rcgh"] },
  { id: "wwqf", val: "crcf * vfvv", deps: ["crcf", "vfvv"] },
  { id: "nvwr", val: "lbcq * wtfw", deps: ["lbcq", "wtfw"] },
  { id: "tcgb", val: "grtt * ngpl", deps: ["grtt", "ngpl"] },
  { id: "tbwl", val: "nbwg + cdwj", deps: ["nbwg", "cdwj"] },
  { id: "vctt", val: 2 },
  { id: "zmrw", val: "zwlq * vsgr", deps: ["zwlq", "vsgr"] },
  { id: "wjbm", val: "djnd * hbsz", deps: ["djnd", "hbsz"] },
  { id: "vbfb", val: 4 },
  { id: "qsrc", val: 5 },
  { id: "tsqv", val: 11 },
  { id: "cwdc", val: "wtgf * lmcc", deps: ["wtgf", "lmcc"] },
  { id: "rtpz", val: "wzdr * tpnl", deps: ["wzdr", "tpnl"] },
  { id: "cgdn", val: "fvjt + lsvs", deps: ["fvjt", "lsvs"] },
  { id: "nncc", val: 2 },
  { id: "zhcs", val: "sdpz + vprl", deps: ["sdpz", "vprl"] },
  { id: "fzbw", val: "dhdz * mhrt", deps: ["dhdz", "mhrt"] },
  { id: "lszf", val: 2 },
  { id: "qmrn", val: 11 },
  { id: "rmhg", val: 3 },
  { id: "wmhw", val: "cdrv + qfvs", deps: ["cdrv", "qfvs"] },
  { id: "clzl", val: 10 },
  { id: "bsjj", val: "ljfw + tscp", deps: ["ljfw", "tscp"] },
  { id: "phjn", val: "fjbs - fmhc", deps: ["fjbs", "fmhc"] },
  { id: "jlqf", val: 5 },
  { id: "mhrt", val: 5 },
  { id: "vhth", val: 3 },
  { id: "lgtl", val: 4 },
  { id: "rjmz", val: 4 },
  { id: "nvzn", val: 7 },
  { id: "ldjj", val: 2 },
  { id: "bslz", val: "rvfl * fwjp", deps: ["rvfl", "fwjp"] },
  { id: "tbrz", val: "hwsd * mdzl", deps: ["hwsd", "mdzl"] },
  { id: "znjw", val: 2 },
  { id: "qmbc", val: 10 },
  { id: "ngbr", val: "nndw * smpz", deps: ["nndw", "smpz"] },
  { id: "lmcc", val: "nnnp + lhbt", deps: ["nnnp", "lhbt"] },
  { id: "znpl", val: "dgcl * lgcl", deps: ["dgcl", "lgcl"] },
  { id: "zcgs", val: "lcmm * tzps", deps: ["lcmm", "tzps"] },
  { id: "mmtj", val: "nzbn + wbgg", deps: ["nzbn", "wbgg"] },
  { id: "vlhl", val: 2 },
  { id: "cfsf", val: 9 },
  { id: "vwjr", val: "lwsw + cnvz", deps: ["lwsw", "cnvz"] },
  { id: "wzdr", val: "znqj / lrzr", deps: ["znqj", "lrzr"] },
  { id: "csmb", val: "vnfp / tswq", deps: ["vnfp", "tswq"] },
  { id: "tsdf", val: 3 },
  { id: "nwbb", val: 2 },
  { id: "hftm", val: 3 },
  { id: "wgtv", val: "qsbv + llhw", deps: ["qsbv", "llhw"] },
  { id: "fzzt", val: "gcrv * cbcf", deps: ["gcrv", "cbcf"] },
  { id: "cpvs", val: "jnjb * dsdv", deps: ["jnjb", "dsdv"] },
  { id: "drtm", val: 7 },
  { id: "jhls", val: "ccjt + drhf", deps: ["ccjt", "drhf"] },
  { id: "gztl", val: "clgr + cfgn", deps: ["clgr", "cfgn"] },
  { id: "njhc", val: 3 },
  { id: "tddb", val: "gzzt * pqvb", deps: ["gzzt", "pqvb"] },
  { id: "vtgn", val: 4 },
  { id: "gbtq", val: "mbbj * rvrr", deps: ["mbbj", "rvrr"] },
  { id: "mwnr", val: 6 },
  { id: "qsdd", val: 2 },
  { id: "ttqg", val: "cfsf + wnhd", deps: ["cfsf", "wnhd"] },
  { id: "dbsp", val: "zwgd + vswb", deps: ["zwgd", "vswb"] },
  { id: "ctwj", val: 20 },
  { id: "ngrp", val: 8 },
  { id: "gfsm", val: "jwwt + vfgw", deps: ["jwwt", "vfgw"] },
  { id: "hgvc", val: "blqj - qgzq", deps: ["blqj", "qgzq"] },
  { id: "qrrb", val: "vrjw * sfws", deps: ["vrjw", "sfws"] },
  { id: "cqwt", val: 7 },
  { id: "lgff", val: 3 },
  { id: "brwz", val: "whtp + pwtn", deps: ["whtp", "pwtn"] },
  { id: "qwzm", val: 4 },
  { id: "zmbs", val: 3 },
  { id: "ltrn", val: 2 },
  { id: "tdsd", val: "gvph + grrm", deps: ["gvph", "grrm"] },
  { id: "rvqj", val: 7 },
  { id: "wtcf", val: "bjbz / tfmf", deps: ["bjbz", "tfmf"] },
  { id: "fqfs", val: "brsw * jjtf", deps: ["brsw", "jjtf"] },
  { id: "qflj", val: "dlct + fswd", deps: ["dlct", "fswd"] },
  { id: "dsdv", val: "rnbh * dcpb", deps: ["rnbh", "dcpb"] },
  { id: "zhqn", val: "trsz * clsd", deps: ["trsz", "clsd"] },
  { id: "gqbb", val: 3 },
  { id: "dntd", val: 8 },
  { id: "bshn", val: "fpzm / mgrz", deps: ["fpzm", "mgrz"] },
  { id: "jccv", val: "ngrv * frvm", deps: ["ngrv", "frvm"] },
  { id: "rlzf", val: 5 },
  { id: "fgzs", val: 6 },
  { id: "zfnb", val: 1 },
  { id: "dpzs", val: 13 },
  { id: "mfbs", val: 11 },
  { id: "dclf", val: 18 },
  { id: "ttvm", val: "lfft * tpwg", deps: ["lfft", "tpwg"] },
  { id: "pczr", val: "zfqj * rghn", deps: ["zfqj", "rghn"] },
  { id: "wcgw", val: 8 },
  { id: "hwjh", val: 3 },
  { id: "tdhn", val: "qlfp + mpwv", deps: ["qlfp", "mpwv"] },
  { id: "cgbh", val: "fbmq + mzrc", deps: ["fbmq", "mzrc"] },
  { id: "cjhm", val: "hgrj + vhcd", deps: ["hgrj", "vhcd"] },
  { id: "jlpf", val: 11 },
  { id: "lvzj", val: "ttch * cdrp", deps: ["ttch", "cdrp"] },
  { id: "qnfv", val: "vqsh * gprf", deps: ["vqsh", "gprf"] },
  { id: "lghp", val: 17 },
  { id: "nptm", val: "wptt * mjcf", deps: ["wptt", "mjcf"] },
  { id: "lwsw", val: 5 },
  { id: "qmnw", val: 4 },
  { id: "jdph", val: 4 },
  { id: "nzbn", val: 4 },
  { id: "wpvt", val: 4 },
  { id: "hvfn", val: "pzfz * rjvj", deps: ["pzfz", "rjvj"] },
  { id: "rpzm", val: 3 },
  { id: "mbmt", val: "ztzz + qjst", deps: ["ztzz", "qjst"] },
  { id: "bsdt", val: 2 },
  { id: "hwsh", val: 2 },
  { id: "tdgj", val: 4 },
  { id: "qwgs", val: "wfvl * snlm", deps: ["wfvl", "snlm"] },
  { id: "ghjv", val: 5 },
  { id: "dvdq", val: 3 },
  { id: "fbfc", val: 2 },
  { id: "rqht", val: 2 },
  { id: "mrvw", val: 2 },
  { id: "gmjj", val: 18 },
  { id: "tfcq", val: "sfhv + vfbq", deps: ["sfhv", "vfbq"] },
  { id: "dgcl", val: "zwgg + hhms", deps: ["zwgg", "hhms"] },
  { id: "lfpr", val: 2 },
  { id: "zgvq", val: 2 },
  { id: "scrn", val: 2 },
  { id: "rcql", val: 5 },
  { id: "nzcj", val: "qpqw * rwrj", deps: ["qpqw", "rwrj"] },
  { id: "nrfp", val: "ggtm + bzbr", deps: ["ggtm", "bzbr"] },
  { id: "cwjz", val: "qlgn + hcdq", deps: ["qlgn", "hcdq"] },
  { id: "dzhn", val: 5 },
  { id: "rpfz", val: 5 },
  { id: "rvfl", val: 4 },
  { id: "tdqd", val: "ghhc * hzvw", deps: ["ghhc", "hzvw"] },
  { id: "fnvm", val: "vwjr + sqbf", deps: ["vwjr", "sqbf"] },
  { id: "spql", val: 3 },
  { id: "mwth", val: "pvcq * fqjz", deps: ["pvcq", "fqjz"] },
  { id: "psnr", val: "pvgt * mgfs", deps: ["pvgt", "mgfs"] },
  { id: "tbfh", val: "gmgz * ngbr", deps: ["gmgz", "ngbr"] },
  { id: "ggwm", val: 3 },
  { id: "ffdw", val: 5 },
  { id: "rbmh", val: "hfws * chfd", deps: ["hfws", "chfd"] },
  { id: "bnqm", val: "fdlb + rssb", deps: ["fdlb", "rssb"] },
  { id: "nnhc", val: "pqsg * zmdq", deps: ["pqsg", "zmdq"] },
  { id: "mfmb", val: 4 },
  { id: "llfp", val: "tbmt * vsct", deps: ["tbmt", "vsct"] },
  { id: "zfwt", val: "hvwm - mqbj", deps: ["hvwm", "mqbj"] },
  { id: "fvcw", val: 17 },
  { id: "vgll", val: 5 },
  { id: "dmms", val: "ncjw * cvgg", deps: ["ncjw", "cvgg"] },
  { id: "fbfp", val: 9 },
  { id: "lwpr", val: "rnlr - vbht", deps: ["rnlr", "vbht"] },
  { id: "fgmj", val: "hddg * pwrl", deps: ["hddg", "pwrl"] },
  { id: "tqcw", val: 20 },
  { id: "bzvv", val: 2 },
  { id: "dtrm", val: 2 },
  { id: "hlzj", val: "rtnc / pnpc", deps: ["rtnc", "pnpc"] },
  { id: "vbns", val: 3 },
  { id: "wdnz", val: "vvgm - cssn", deps: ["vvgm", "cssn"] },
  { id: "pztz", val: "vpsj + dpvg", deps: ["vpsj", "dpvg"] },
  { id: "mhvf", val: "hjvn + fhcc", deps: ["hjvn", "fhcc"] },
  { id: "pjbl", val: "qrrw * sshj", deps: ["qrrw", "sshj"] },
  { id: "wgfv", val: "rdvw - wwqn", deps: ["rdvw", "wwqn"] },
  { id: "jjcv", val: "scvw - qrrb", deps: ["scvw", "qrrb"] },
  { id: "jtvq", val: "qgvj + bvmt", deps: ["qgvj", "bvmt"] },
  { id: "sshd", val: "tdsq + vljq", deps: ["tdsq", "vljq"] },
  { id: "shbw", val: "nhhl + vnwg", deps: ["nhhl", "vnwg"] },
  { id: "cpnh", val: "vcbr + gmdn", deps: ["vcbr", "gmdn"] },
  { id: "zfml", val: "bndf * cdtn", deps: ["bndf", "cdtn"] },
  { id: "rggc", val: "mgvc - ltjv", deps: ["mgvc", "ltjv"] },
  { id: "vrzm", val: "bnsf + vhvt", deps: ["bnsf", "vhvt"] },
  { id: "zjpj", val: 5 },
  { id: "fpzs", val: 3 },
  { id: "vtsh", val: 5 },
  { id: "tjpg", val: 2 },
  { id: "splt", val: 2 },
  { id: "gfsr", val: "vzff + wdbt", deps: ["vzff", "wdbt"] },
  { id: "qvcm", val: 2 },
  { id: "rssb", val: "bccr * vmsh", deps: ["bccr", "vmsh"] },
  { id: "tcpc", val: "pbpl + qflj", deps: ["pbpl", "qflj"] },
  { id: "djnd", val: 4 },
  { id: "bgsh", val: "bwst - gdpf", deps: ["bwst", "gdpf"] },
  { id: "pjnv", val: "bsgf * bmfb", deps: ["bsgf", "bmfb"] },
  { id: "rlph", val: "zwwn / tsgr", deps: ["zwwn", "tsgr"] },
  { id: "hgpp", val: 6 },
  { id: "gcsv", val: "qvhb * tsqv", deps: ["qvhb", "tsqv"] },
  { id: "nlfv", val: 13 },
  { id: "dwcz", val: 6 },
  { id: "sbwc", val: 9 },
  { id: "smcs", val: "plgr * hqpb", deps: ["plgr", "hqpb"] },
  { id: "tdsq", val: "hnmh * cvml", deps: ["hnmh", "cvml"] },
  { id: "gncn", val: "rmbb * pjnh", deps: ["rmbb", "pjnh"] },
  { id: "mgdb", val: "lfzj + dhzf", deps: ["lfzj", "dhzf"] },
  { id: "hrbp", val: "dltm * rlph", deps: ["dltm", "rlph"] },
  { id: "nshc", val: "jqtn - prfd", deps: ["jqtn", "prfd"] },
  { id: "qhmh", val: 2 },
  { id: "qfdz", val: 2 },
  { id: "dmsz", val: "hrbp + nzjs", deps: ["hrbp", "nzjs"] },
  { id: "dzfp", val: 13 },
  { id: "fmlh", val: "zscv * ptns", deps: ["zscv", "ptns"] },
  { id: "root", val: "fflg + qwqj", deps: ["fflg", "qwqj"] },
  { id: "jntz", val: 8 },
  { id: "hrlf", val: 4 },
  { id: "nwcq", val: "hzdl * mbmt", deps: ["hzdl", "mbmt"] },
  { id: "bmsz", val: 4 },
  { id: "tzct", val: 4 },
  { id: "csmc", val: 4 },
  { id: "trzn", val: 5 },
  { id: "wwqn", val: "vfps + gmgw", deps: ["vfps", "gmgw"] },
  { id: "hrmp", val: "rjgj + lvwd", deps: ["rjgj", "lvwd"] },
  { id: "tzbj", val: 12 },
  { id: "qvhb", val: "msfg + rtfg", deps: ["msfg", "rtfg"] },
  { id: "blgt", val: 2 },
  { id: "qbnw", val: 2 },
  { id: "mqww", val: "qdhg / vpgz", deps: ["qdhg", "vpgz"] },
  { id: "bmqm", val: 3 },
  { id: "btfj", val: "nwcq + lvnw", deps: ["nwcq", "lvnw"] },
  { id: "lzch", val: "tqnd * gpzw", deps: ["tqnd", "gpzw"] },
  { id: "mnnf", val: "pcpj / llfp", deps: ["pcpj", "llfp"] },
  { id: "nzdr", val: "cvqs * wbnl", deps: ["cvqs", "wbnl"] },
  { id: "dgwd", val: 16 },
  { id: "jnvz", val: "zwfh * gpbr", deps: ["zwfh", "gpbr"] },
  { id: "mfnj", val: "gvlj / phbz", deps: ["gvlj", "phbz"] },
  { id: "dlbb", val: 3 },
  { id: "btdz", val: 3 },
  { id: "hwgr", val: "lsfh + zqnb", deps: ["lsfh", "zqnb"] },
  { id: "cdrp", val: "jnjr - vvlr", deps: ["jnjr", "vvlr"] },
  { id: "mvmm", val: 4 },
  { id: "mmvm", val: 15 },
  { id: "crcf", val: 2 },
  { id: "glfs", val: 3 },
  { id: "qcpl", val: "hftm + chpt", deps: ["hftm", "chpt"] },
  { id: "vpsj", val: "jjzh * vcpv", deps: ["jjzh", "vcpv"] },
  { id: "rnzj", val: 1 },
  { id: "stsw", val: "nslg * lljf", deps: ["nslg", "lljf"] },
  { id: "wlfc", val: "brgr * qfdz", deps: ["brgr", "qfdz"] },
  { id: "pwld", val: 1 },
  { id: "htwq", val: "fmsd + vjvt", deps: ["fmsd", "vjvt"] },
  { id: "bznq", val: "dwcq + hhjc", deps: ["dwcq", "hhjc"] },
  { id: "lznl", val: "zpgj * wbfv", deps: ["zpgj", "wbfv"] },
  { id: "jzvq", val: "ncvj + fzbp", deps: ["ncvj", "fzbp"] },
  { id: "dwll", val: 5 },
  { id: "svzn", val: "dflj * zdzp", deps: ["dflj", "zdzp"] },
  { id: "glsv", val: 4 },
  { id: "whtp", val: 5 },
  { id: "bvll", val: "njwt + clhb", deps: ["njwt", "clhb"] },
  { id: "llgt", val: 9 },
  { id: "nmzb", val: "mpvq + csmv", deps: ["mpvq", "csmv"] },
  { id: "mfdm", val: 3 },
  { id: "zmvp", val: "fbfp + lbfn", deps: ["fbfp", "lbfn"] },
  { id: "cqsz", val: "rbvv + mnsw", deps: ["rbvv", "mnsw"] },
  { id: "ctpj", val: "jmmh * hjzt", deps: ["jmmh", "hjzt"] },
  { id: "lvwv", val: 2 },
  { id: "mnvz", val: "mblw * bmqm", deps: ["mblw", "bmqm"] },
  { id: "ggtm", val: 16 },
  { id: "shzg", val: "fmlh + rvjr", deps: ["fmlh", "rvjr"] },
  { id: "hhdd", val: 3 },
  { id: "qlgn", val: "lhcw * dgmj", deps: ["lhcw", "dgmj"] },
  { id: "tnns", val: "wdfw * stmg", deps: ["wdfw", "stmg"] },
  { id: "wwbl", val: "jlqf * nqgj", deps: ["jlqf", "nqgj"] },
  { id: "fnwh", val: 2 },
  { id: "szdh", val: "bsjj * srdl", deps: ["bsjj", "srdl"] },
  { id: "gvph", val: "jtvq + mzvj", deps: ["jtvq", "mzvj"] },
  { id: "lcwg", val: 3 },
  { id: "tnhv", val: "fsfw + jzvq", deps: ["fsfw", "jzvq"] },
  { id: "lrzr", val: 2 },
  { id: "pjnh", val: 2 },
  { id: "njjm", val: "wtwl + nnhc", deps: ["wtwl", "nnhc"] },
  { id: "qdpr", val: 6 },
  { id: "bsvn", val: "ltjg - wpvt", deps: ["ltjg", "wpvt"] },
  { id: "rhgg", val: "wqnn * mnzn", deps: ["wqnn", "mnzn"] },
  { id: "gvnm", val: 14 },
  { id: "qhzs", val: 13 },
  { id: "gjmc", val: 2 },
  { id: "ccwv", val: "zspc * mrpf", deps: ["zspc", "mrpf"] },
  { id: "dgmj", val: 7 },
  { id: "vnmg", val: "pbds * dscl", deps: ["pbds", "dscl"] },
  { id: "cppb", val: "bwws - hqbh", deps: ["bwws", "hqbh"] },
  { id: "fjbs", val: "zfnf / mswd", deps: ["zfnf", "mswd"] },
  { id: "wprz", val: "pzfp - svrr", deps: ["pzfp", "svrr"] },
  { id: "mrgn", val: 1 },
  { id: "lwlq", val: 2 },
  { id: "ptns", val: 2 },
  { id: "lzjb", val: "lvhw * mvvj", deps: ["lvhw", "mvvj"] },
  { id: "flwh", val: "qgmm + bmdf", deps: ["qgmm", "bmdf"] },
  { id: "wzql", val: 13 },
  { id: "fwrb", val: "gcnz * wcfb", deps: ["gcnz", "wcfb"] },
  { id: "hqpb", val: 2 },
  { id: "zwwn", val: "tbrn + bwhf", deps: ["tbrn", "bwhf"] },
  { id: "dnbw", val: 2 },
  { id: "lsgm", val: "lclm + qhrf", deps: ["lclm", "qhrf"] },
  { id: "lmbw", val: "msdv * hlnf", deps: ["msdv", "hlnf"] },
  { id: "pvqf", val: "fwnw + hpcq", deps: ["fwnw", "hpcq"] },
  { id: "mgvc", val: "lmbw + jdfl", deps: ["lmbw", "jdfl"] },
  { id: "jsrt", val: "jccv / zpmc", deps: ["jccv", "zpmc"] },
  { id: "dfrm", val: 5 },
  { id: "dfwb", val: 2 },
  { id: "rwph", val: "rsvv + ftsg", deps: ["rsvv", "ftsg"] },
  { id: "tmnv", val: 4 },
  { id: "wttd", val: 2 },
  { id: "pvhp", val: 3 },
  { id: "gsnd", val: 5 },
  { id: "rwgc", val: "fmmr + gghq", deps: ["fmmr", "gghq"] },
  { id: "mjfs", val: "lzqq * vfrg", deps: ["lzqq", "vfrg"] },
  { id: "rjcr", val: 6 },
  { id: "hmgr", val: 15 },
  { id: "mclj", val: 7 },
  { id: "sfws", val: "fvnp + mjqp", deps: ["fvnp", "mjqp"] },
  { id: "msfv", val: 1 },
  { id: "snmd", val: 2 },
  { id: "thjb", val: "bgcw / tcml", deps: ["bgcw", "tcml"] },
  { id: "mvnf", val: 6 },
  { id: "bvcg", val: "cpwd - jqvv", deps: ["cpwd", "jqvv"] },
  { id: "nqhs", val: "mcds * vhql", deps: ["mcds", "vhql"] },
  { id: "dvhf", val: "tbcl - cssq", deps: ["tbcl", "cssq"] },
  { id: "qnbl", val: "qjff + qznr", deps: ["qjff", "qznr"] },
  { id: "vgnr", val: 3 },
  { id: "czwb", val: "jbjz + qpwn", deps: ["jbjz", "qpwn"] },
  { id: "rdlm", val: 2 },
  { id: "hcwj", val: "tjbr - szqq", deps: ["tjbr", "szqq"] },
  { id: "hrfz", val: "nvwr + jdcr", deps: ["nvwr", "jdcr"] },
  { id: "mjcf", val: 5 },
  { id: "qjbg", val: "fmsj + tbfh", deps: ["fmsj", "tbfh"] },
  { id: "jtsg", val: 2 },
  { id: "hscp", val: "ftmv + fgsl", deps: ["ftmv", "fgsl"] },
  { id: "ltft", val: "fvcc + pttb", deps: ["fvcc", "pttb"] },
  { id: "qsbv", val: 1 },
  { id: "rhcb", val: "cwcp * pvhp", deps: ["cwcp", "pvhp"] },
  { id: "vcmc", val: 5 },
  { id: "dbzs", val: 3 },
  { id: "grcr", val: "lvsm * btqf", deps: ["lvsm", "btqf"] },
  { id: "hsfg", val: "qgrw - pfrn", deps: ["qgrw", "pfrn"] },
  { id: "mvlt", val: "dlbp + scwz", deps: ["dlbp", "scwz"] },
  { id: "fbmq", val: 3 },
  { id: "bgcw", val: "njwf * stsz", deps: ["njwf", "stsz"] },
  { id: "tshf", val: 4 },
  { id: "cgpw", val: "jmvh * qncr", deps: ["jmvh", "qncr"] },
  { id: "slnn", val: 3 },
  { id: "lwsf", val: 9 },
  { id: "lmlf", val: 11 },
  { id: "qdgp", val: 2 },
  { id: "tnvv", val: 3 },
  { id: "rbgl", val: 3 },
  { id: "djmp", val: 2 },
  { id: "vlmz", val: "dnrd / nrqr", deps: ["dnrd", "nrqr"] },
  { id: "fwbg", val: 2 },
  { id: "gqjl", val: "vsrj + zjlz", deps: ["vsrj", "zjlz"] },
  { id: "vfgw", val: "bfgl + llcs", deps: ["bfgl", "llcs"] },
  { id: "dlsm", val: "qvjv / vbfb", deps: ["qvjv", "vbfb"] },
  { id: "hgjg", val: "ttvm - lttp", deps: ["ttvm", "lttp"] },
  { id: "lsvs", val: "wslv * zqfz", deps: ["wslv", "zqfz"] },
  { id: "tbgp", val: 2 },
  { id: "vscm", val: "rlbh + zfqd", deps: ["rlbh", "zfqd"] },
  { id: "hhzn", val: "ltgp + mclj", deps: ["ltgp", "mclj"] },
  { id: "qghq", val: 2 },
  { id: "tvcv", val: 3 },
  { id: "brsw", val: 2 },
  { id: "tgsp", val: "qcfh + jfpm", deps: ["qcfh", "jfpm"] },
  { id: "strm", val: "ssbj * sshh", deps: ["ssbj", "sshh"] },
  { id: "zpgj", val: 3 },
  { id: "qlml", val: "ttbb + clns", deps: ["ttbb", "clns"] },
  { id: "jhmp", val: 3 },
  { id: "bmcv", val: "vcmc + szcz", deps: ["vcmc", "szcz"] },
  { id: "lltd", val: 3 },
  { id: "ptrc", val: 3 },
  { id: "vggn", val: "rgcj + fczs", deps: ["rgcj", "fczs"] },
  { id: "nlps", val: "hbpp * fhpl", deps: ["hbpp", "fhpl"] },
  { id: "tbfn", val: "mrzs + vbnt", deps: ["mrzs", "vbnt"] },
  { id: "jvtv", val: 9 },
  { id: "jsbd", val: 8 },
  { id: "hdvg", val: 2 },
  { id: "hdhh", val: 9 },
  { id: "bsjc", val: 5 },
  { id: "hdmr", val: "pjzs + szzn", deps: ["pjzs", "szzn"] },
  { id: "pcpj", val: "jlvs - zhcf", deps: ["jlvs", "zhcf"] },
  { id: "nvdr", val: 1 },
  { id: "fhht", val: 3 },
  { id: "dthh", val: 3 },
  { id: "bdqf", val: "rdhz * swcb", deps: ["rdhz", "swcb"] },
  { id: "cvbc", val: 3 },
  { id: "bghm", val: "bttg + dhnv", deps: ["bttg", "dhnv"] },
  { id: "wrnb", val: "nmpn * pmjm", deps: ["nmpn", "pmjm"] },
  { id: "srsp", val: 4 },
  { id: "cnlj", val: 4 },
  { id: "cfcm", val: 1 },
  { id: "ztzz", val: "drnq * ftrq", deps: ["drnq", "ftrq"] },
  { id: "fzpg", val: 5 },
  { id: "mpht", val: 2 },
  { id: "vdgh", val: "gltp / sqvg", deps: ["gltp", "sqvg"] },
  { id: "tzwh", val: 8 },
  { id: "pjzs", val: 3 },
  { id: "pjvt", val: "tntl * nwcw", deps: ["tntl", "nwcw"] },
  { id: "mpwv", val: "wmmh * svng", deps: ["wmmh", "svng"] },
  { id: "cmjj", val: "spql * trrq", deps: ["spql", "trrq"] },
  { id: "dcpb", val: 3 },
  { id: "lczq", val: "rzqh - rhfq", deps: ["rzqh", "rhfq"] },
  { id: "dtrv", val: "fvvq + qcsd", deps: ["fvvq", "qcsd"] },
  { id: "fgsl", val: 2 },
  { id: "jwlt", val: "fsnw * jshj", deps: ["fsnw", "jshj"] },
  { id: "scgl", val: "vddr * fzvr", deps: ["vddr", "fzvr"] },
  { id: "hgrj", val: "lqpq * qjng", deps: ["lqpq", "qjng"] },
  { id: "pbbh", val: "mvmm * psnz", deps: ["mvmm", "psnz"] },
  { id: "hbws", val: "pvmm + gfsm", deps: ["pvmm", "gfsm"] },
  { id: "mgsg", val: 2 },
  { id: "zcbf", val: 2 },
  { id: "bjct", val: "mznq * vvfm", deps: ["mznq", "vvfm"] },
  { id: "cvlm", val: "cqdt * mjhn", deps: ["cqdt", "mjhn"] },
  { id: "nnmf", val: "zshl * tnnd", deps: ["zshl", "tnnd"] },
  { id: "bbsl", val: 3 },
  { id: "trtc", val: 3 },
  { id: "frpb", val: "sfwh + czbb", deps: ["sfwh", "czbb"] },
  { id: "lggv", val: "gwlv * dbjt", deps: ["gwlv", "dbjt"] },
  { id: "rghn", val: "ctgh + chgr", deps: ["ctgh", "chgr"] },
  { id: "znfp", val: "tjpg * mbts", deps: ["tjpg", "mbts"] },
  { id: "mdzl", val: 3 },
  { id: "brgr", val: "cqpr + gqlj", deps: ["cqpr", "gqlj"] },
  { id: "mgfs", val: "lznl + psgd", deps: ["lznl", "psgd"] },
  { id: "fmsd", val: "clhv * qfnt", deps: ["clhv", "qfnt"] },
  { id: "pwwr", val: 3 },
  { id: "twtm", val: "cppb * qqnw", deps: ["cppb", "qqnw"] },
  { id: "cngv", val: "rrwg * vrwm", deps: ["rrwg", "vrwm"] },
  { id: "vqsh", val: 7 },
  { id: "qzvb", val: 3 },
  { id: "qmhm", val: 2 },
  { id: "bbbs", val: "wvcp + ngzh", deps: ["wvcp", "ngzh"] },
  { id: "grwc", val: "mjsv * pvpg", deps: ["mjsv", "pvpg"] },
  { id: "lntm", val: 4 },
  { id: "qddv", val: 14 },
  { id: "csqd", val: "tnhv * rntr", deps: ["tnhv", "rntr"] },
  { id: "wnbz", val: 2 },
  { id: "hqbh", val: "crsd + cwjz", deps: ["crsd", "cwjz"] },
  { id: "ssqn", val: 4 },
  { id: "szqq", val: "qzqz + fgzs", deps: ["qzqz", "fgzs"] },
  { id: "hzlv", val: "brwz - sqwc", deps: ["brwz", "sqwc"] },
  { id: "nbpj", val: 4 },
  { id: "zttg", val: 3 },
  { id: "dbjt", val: "pjqs - zlbl", deps: ["pjqs", "zlbl"] },
  { id: "cfwg", val: 2 },
  { id: "wsgm", val: "nslm * vhtd", deps: ["nslm", "vhtd"] },
  { id: "wwsh", val: "prpw / vtwp", deps: ["prpw", "vtwp"] },
  { id: "svnq", val: 2 },
  { id: "cbqv", val: 7 },
  { id: "qcfh", val: "wwsh + lmvw", deps: ["wwsh", "lmvw"] },
  { id: "lcmm", val: 3 },
  { id: "ltjg", val: "bjmz * dfvp", deps: ["bjmz", "dfvp"] },
  { id: "jwwt", val: "vpnb - fhwz", deps: ["vpnb", "fhwz"] },
  { id: "jhqv", val: "wqcc * cnhr", deps: ["wqcc", "cnhr"] },
  { id: "tbmt", val: 3 },
  { id: "vbvl", val: 5 },
  { id: "wgpf", val: "btdz + jgjs", deps: ["btdz", "jgjs"] },
  { id: "tpgj", val: 3 },
  { id: "nqgj", val: 3 },
  { id: "gmgp", val: "qljc + njwq", deps: ["qljc", "njwq"] },
  { id: "zcgt", val: "rmqp - mscr", deps: ["rmqp", "mscr"] },
  { id: "prpb", val: "bmqg + smcz", deps: ["bmqg", "smcz"] },
  { id: "rglt", val: 2 },
  { id: "cqmg", val: "vrhf * mftc", deps: ["vrhf", "mftc"] },
  { id: "tvpl", val: 5 },
  { id: "hhms", val: "mmlc - pcpc", deps: ["mmlc", "pcpc"] },
  { id: "tsgr", val: 2 },
  { id: "bngl", val: 5 },
  { id: "ghhc", val: 5 },
  { id: "hhvl", val: 3 },
  { id: "sfsh", val: 5 },
  { id: "jsdz", val: 2 },
  { id: "qpqw", val: "hfrp + jfnm", deps: ["hfrp", "jfnm"] },
  { id: "ftrq", val: 2 },
  { id: "mcwv", val: 3 },
  { id: "bbnr", val: "cbhg * fvhn", deps: ["cbhg", "fvhn"] },
  { id: "vslg", val: 2 },
  { id: "zmsb", val: 6 },
  { id: "jzdb", val: "jbld + fprq", deps: ["jbld", "fprq"] },
  { id: "gbzj", val: 10 },
  { id: "scwj", val: 2 },
  { id: "wbtw", val: 16 },
  { id: "vqts", val: 5 },
  { id: "vmhh", val: "zmsl + wpzb", deps: ["zmsl", "wpzb"] },
  { id: "hjdp", val: "zbzd * cnfb", deps: ["zbzd", "cnfb"] },
  { id: "rdhz", val: 7 },
  { id: "mgbt", val: 2 },
  { id: "zwlq", val: "nvjt + jwvl", deps: ["nvjt", "jwvl"] },
  { id: "sstw", val: 2 },
  { id: "cssn", val: 2 },
  { id: "qwhz", val: 2 },
  { id: "dzvc", val: 2 },
  { id: "vjpw", val: 3 },
  { id: "gzmd", val: 2 },
  { id: "rntr", val: "bqgf * mgjf", deps: ["bqgf", "mgjf"] },
  { id: "gpws", val: 5 },
  { id: "srjv", val: "wpzq + hjdp", deps: ["wpzq", "hjdp"] },
  { id: "bwmt", val: "nhzl * gvrr", deps: ["nhzl", "gvrr"] },
  { id: "dczf", val: 4 },
  { id: "hfrp", val: "qlnb + fsrb", deps: ["qlnb", "fsrb"] },
  { id: "fmtb", val: "hgrw + lcrh", deps: ["hgrw", "lcrh"] },
  { id: "bwst", val: "jsdz * dghh", deps: ["jsdz", "dghh"] },
  { id: "znqj", val: "vjrf * scwj", deps: ["vjrf", "scwj"] },
  { id: "lgcl", val: 2 },
  { id: "jhwh", val: 7 },
  { id: "fnjg", val: "lcwm + rtph", deps: ["lcwm", "rtph"] },
  { id: "rflv", val: "qsrc + gvcw", deps: ["qsrc", "gvcw"] },
  { id: "vrbm", val: 2 },
  { id: "qdpv", val: "mdlj * ltlm", deps: ["mdlj", "ltlm"] },
  { id: "vgqb", val: "zjmv * fdjb", deps: ["zjmv", "fdjb"] },
  { id: "mjqp", val: "bdqf * wbqd", deps: ["bdqf", "wbqd"] },
  { id: "gwwd", val: 4 },
  { id: "htzz", val: 2 },
  { id: "clgr", val: 13 },
  { id: "zqzf", val: 6 },
  { id: "rqch", val: 2 },
  { id: "lmjc", val: 2 },
  { id: "lvvg", val: "prjz * rhcb", deps: ["prjz", "rhcb"] },
  { id: "tgsl", val: "rpzm * czlm", deps: ["rpzm", "czlm"] },
  { id: "vwsr", val: 4 },
  { id: "zsmj", val: "jtgt + hlgn", deps: ["jtgt", "hlgn"] },
  { id: "rvjr", val: "sdgr * dnbw", deps: ["sdgr", "dnbw"] },
  { id: "cglj", val: 3 },
  { id: "rprq", val: "mrgf + vlpq", deps: ["mrgf", "vlpq"] },
  { id: "psdf", val: "qhmh * fmnq", deps: ["qhmh", "fmnq"] },
  { id: "mnht", val: "zhgh * bmsz", deps: ["zhgh", "bmsz"] },
  { id: "pzsl", val: "vscm / dczf", deps: ["vscm", "dczf"] },
  { id: "tfhb", val: "vdgh + mrjn", deps: ["vdgh", "mrjn"] },
  { id: "fsfw", val: "wdgw + jncn", deps: ["wdgw", "jncn"] },
  { id: "fwss", val: 3 },
  { id: "frgw", val: "crmt + bnhp", deps: ["crmt", "bnhp"] },
  { id: "ttqw", val: 2 },
  { id: "cbvz", val: "zfmh * hvqd", deps: ["zfmh", "hvqd"] },
  { id: "gcnz", val: "jjzj - vmhh", deps: ["jjzj", "vmhh"] },
  { id: "drfh", val: "nqbh + zpdl", deps: ["nqbh", "zpdl"] },
  { id: "tvbv", val: 3 },
  { id: "gvvz", val: 15 },
  { id: "qwdt", val: 2 },
  { id: "vdnw", val: 14 },
  { id: "zfnf", val: "mfwn + jzsr", deps: ["mfwn", "jzsr"] },
  { id: "ghzf", val: "rvqj * zbcv", deps: ["rvqj", "zbcv"] },
  { id: "wcch", val: "wpnt + vmbv", deps: ["wpnt", "vmbv"] },
  { id: "vzzm", val: "snmd * ndgd", deps: ["snmd", "ndgd"] },
  { id: "qprd", val: "zzhd * rvtp", deps: ["zzhd", "rvtp"] },
  { id: "gsls", val: 10 },
  { id: "hglj", val: "vqts * tdfv", deps: ["vqts", "tdfv"] },
  { id: "gcdr", val: "bvcg / nldq", deps: ["bvcg", "nldq"] },
  { id: "mhzn", val: "vslg + mlrn", deps: ["vslg", "mlrn"] },
  { id: "svfq", val: "prbq - gcpq", deps: ["prbq", "gcpq"] },
  { id: "pftm", val: "mwqn * qbnw", deps: ["mwqn", "qbnw"] },
  { id: "dvcf", val: "hhpz / dzcb", deps: ["hhpz", "dzcb"] },
  { id: "vgmc", val: 5 },
  { id: "qclz", val: 6 },
  { id: "cbvw", val: "bcjg * hjgn", deps: ["bcjg", "hjgn"] },
  { id: "qvcb", val: 3 },
  { id: "brfn", val: 3 },
  { id: "jwnd", val: "bmjd + dbww", deps: ["bmjd", "dbww"] },
  { id: "wfgp", val: "hvcd * tbrz", deps: ["hvcd", "tbrz"] },
  { id: "fwls", val: 10 },
  { id: "zczn", val: "cqmg * nzdr", deps: ["cqmg", "nzdr"] },
  { id: "zgsg", val: "qnjz * jsng", deps: ["qnjz", "jsng"] },
  { id: "wtnv", val: 3 },
  { id: "hbgd", val: "tptz + wprz", deps: ["tptz", "wprz"] },
  { id: "ldlr", val: "brgj * vgll", deps: ["brgj", "vgll"] },
  { id: "fqsp", val: "bfdn * rzlc", deps: ["bfdn", "rzlc"] },
  { id: "pjqs", val: "bznq / dqdc", deps: ["bznq", "dqdc"] },
  { id: "rwmr", val: "cgqw + clbj", deps: ["cgqw", "clbj"] },
  { id: "hcdq", val: "cbvw * wvpj", deps: ["cbvw", "wvpj"] },
  { id: "hnmh", val: "jjcv * fwfn", deps: ["jjcv", "fwfn"] },
  { id: "svrr", val: 11 },
  { id: "zszn", val: "blph * szhf", deps: ["blph", "szhf"] },
  { id: "ngft", val: 5 },
  { id: "qljc", val: 5 },
  { id: "ttwj", val: 2 },
  { id: "szhq", val: 3 },
  { id: "trrq", val: 5 },
  { id: "nbwg", val: 12 },
  { id: "clgw", val: "vztr * rfmp", deps: ["vztr", "rfmp"] },
  { id: "llpr", val: "wgpf + qvjr", deps: ["wgpf", "qvjr"] },
  { id: "ndwb", val: "vfrq * fcgc", deps: ["vfrq", "fcgc"] },
  { id: "zzsq", val: 4 },
  { id: "mvvn", val: "hbpf - qjbg", deps: ["hbpf", "qjbg"] },
  { id: "tfmb", val: 4 },
  { id: "tmvd", val: 6 },
  { id: "lqbn", val: 5 },
  { id: "mrjn", val: "nrpj - swvr", deps: ["nrpj", "swvr"] },
  { id: "qdzj", val: 11 },
  { id: "psgd", val: 1 },
  { id: "fwqj", val: 2 },
  { id: "nhjj", val: "vjdg * gwww", deps: ["vjdg", "gwww"] },
  { id: "vfrq", val: "rszm * lnqt", deps: ["rszm", "lnqt"] },
  { id: "ltjv", val: 4 },
  { id: "gcql", val: "ttfq * wwzn", deps: ["ttfq", "wwzn"] },
  { id: "qddm", val: "nnfq - mrvw", deps: ["nnfq", "mrvw"] },
  { id: "hbpf", val: "qffl * qzts", deps: ["qffl", "qzts"] },
  { id: "mbzh", val: "thmh * phjn", deps: ["thmh", "phjn"] },
  { id: "wjnl", val: "flvc + srsp", deps: ["flvc", "srsp"] },
  { id: "wcct", val: "lvtj * splt", deps: ["lvtj", "splt"] },
  { id: "jwqc", val: "mqnh + vfhb", deps: ["mqnh", "vfhb"] },
  { id: "bfgl", val: "mfbs + zttr", deps: ["mfbs", "zttr"] },
  { id: "rscv", val: 2 },
  { id: "dqhd", val: "cfhr + fpjv", deps: ["cfhr", "fpjv"] },
  { id: "pwqg", val: 16 },
  { id: "jznt", val: "humn - sbhj", deps: ["humn", "sbhj"] },
  { id: "rqgl", val: "tlth * vsbd", deps: ["tlth", "vsbd"] },
  { id: "mrpf", val: "gmjj + cgbh", deps: ["gmjj", "cgbh"] },
  { id: "cffd", val: 4 },
  { id: "sbhv", val: 4 },
  { id: "vhtd", val: 4 },
  { id: "jpcj", val: "zczn + pbbh", deps: ["zczn", "pbbh"] },
  { id: "cqzw", val: "dtgc + svsh", deps: ["dtgc", "svsh"] },
  { id: "mrgf", val: "bqhg * lmfg", deps: ["bqhg", "lmfg"] },
  { id: "pzws", val: 2 },
  { id: "pwjf", val: "wtrr * sftj", deps: ["wtrr", "sftj"] },
  { id: "gwlg", val: 5 },
  { id: "tqmc", val: "jjmp * dfzh", deps: ["jjmp", "dfzh"] },
  { id: "bhrb", val: 16 },
  { id: "djzc", val: 2 },
  { id: "rrwg", val: "wzdd * cftg", deps: ["wzdd", "cftg"] },
  { id: "lrlr", val: "fmtb + jdjb", deps: ["fmtb", "jdjb"] },
  { id: "rwrj", val: 2 },
  { id: "mcnm", val: 2 },
  { id: "lrbl", val: 2 },
  { id: "bqzt", val: 3 },
  { id: "qwrs", val: "ltbn * rbgl", deps: ["ltbn", "rbgl"] },
  { id: "zrhp", val: 3 },
  { id: "ttbb", val: "dhdh - jhwh", deps: ["dhdh", "jhwh"] },
  { id: "rmbb", val: "qmjs / gltv", deps: ["qmjs", "gltv"] },
  { id: "bhcp", val: 11 },
  { id: "vvmc", val: "tnns + fzpg", deps: ["tnns", "fzpg"] },
  { id: "fhwz", val: "hncs + vwrr", deps: ["hncs", "vwrr"] },
  { id: "csqb", val: 2 },
  { id: "fbmn", val: "nhcj + jhgd", deps: ["nhcj", "jhgd"] },
  { id: "szhf", val: 3 },
  { id: "dfhh", val: "sfsh * rlzf", deps: ["sfsh", "rlzf"] },
  { id: "lcvr", val: "qgnb * ggdl", deps: ["qgnb", "ggdl"] },
  { id: "njwf", val: 2 },
  { id: "hvwm", val: "djmp * dgwd", deps: ["djmp", "dgwd"] },
  { id: "rsgp", val: 9 },
  { id: "vhhg", val: "qffm * zmhl", deps: ["qffm", "zmhl"] },
  { id: "ftzh", val: 7 },
  { id: "ddhj", val: 2 },
  { id: "tlth", val: 5 },
  { id: "qmpb", val: 3 },
  { id: "zfmh", val: "mjfs + cfcm", deps: ["mjfs", "cfcm"] },
  { id: "qffm", val: 2 },
]

export const sample = [
  { id: "root", val: "pppw + sjmn", deps: ["pppw", "sjmn"] },
  { id: "dbpl", val: 5 },
  { id: "cczh", val: "sllz + lgvd", deps: ["sllz", "lgvd"] },
  { id: "zczc", val: 2 },
  { id: "ptdq", val: "humn - dvpt", deps: ["humn", "dvpt"] },
  { id: "dvpt", val: 3 },
  { id: "lfqf", val: 4 },
  { id: "humn", val: 5 },
  { id: "ljgn", val: 2 },
  { id: "sjmn", val: "drzm * dbpl", deps: ["drzm", "dbpl"] },
  { id: "sllz", val: 4 },
  { id: "pppw", val: "cczh / lfqf", deps: ["cczh", "lfqf"] },
  { id: "lgvd", val: "ljgn * ptdq", deps: ["ljgn", "ptdq"] },
  { id: "drzm", val: "hmdt - zczc", deps: ["hmdt", "zczc"] },
  { id: "hmdt", val: 32 },
]
