export default {
  TU: { flowRate: 0, nodes: ["XG", "ID"] },
  RR: { flowRate: 0, nodes: ["BO", "NF"] },
  UB: { flowRate: 0, nodes: ["GY", "AC"] },
  OP: { flowRate: 0, nodes: ["OU", "DI"] },
  KL: { flowRate: 21, nodes: ["QZ", "QT"] },
  QA: { flowRate: 0, nodes: ["AC", "XM"] },
  CI: { flowRate: 0, nodes: ["RH", "BC"] },
  NZ: { flowRate: 0, nodes: ["TO", "OU"] },
  MY: { flowRate: 0, nodes: ["BO", "KV"] },
  GY: { flowRate: 0, nodes: ["KW", "UB"] },
  ZB: { flowRate: 0, nodes: ["YS", "XH"] },
  OU: { flowRate: 8, nodes: ["ZV", "YA", "NZ", "OP"] },
  KV: { flowRate: 0, nodes: ["MJ", "MY"] },
  BC: { flowRate: 0, nodes: ["TO", "CI"] },
  YS: { flowRate: 22, nodes: ["ZB", "UE"] },
  CD: { flowRate: 25, nodes: ["LS", "FO"] },
  ID: { flowRate: 11, nodes: ["BI", "TU"] },
  RN: { flowRate: 0, nodes: ["AC", "CN"] },
  HH: { flowRate: 0, nodes: ["GI", "KW"] },
  QZ: { flowRate: 0, nodes: ["AC", "KL"] },
  BI: { flowRate: 0, nodes: ["OI", "ID"] },
  NF: { flowRate: 0, nodes: ["RR", "OI"] },
  CH: { flowRate: 0, nodes: ["AA", "MJ"] },
  UE: { flowRate: 0, nodes: ["LS", "YS"] },
  ZV: { flowRate: 0, nodes: ["OU", "AA"] },
  YM: { flowRate: 0, nodes: ["OI", "AA"] },
  IG: { flowRate: 0, nodes: ["TO", "QL"] },
  FO: { flowRate: 0, nodes: ["CD", "KW"] },
  AC: { flowRate: 4, nodes: ["KC", "RN", "QA", "QZ", "UB"] },
  JO: { flowRate: 0, nodes: ["RH", "DI"] },
  OI: { flowRate: 10, nodes: ["VS", "BI", "CN", "NF", "YM"] },
  MJ: { flowRate: 3, nodes: ["KV", "XM", "ER", "CH", "BS"] },
  KC: { flowRate: 0, nodes: ["AC", "AA"] },
  ER: { flowRate: 0, nodes: ["MJ", "VS"] },
  CV: { flowRate: 0, nodes: ["TO", "IU"] },
  RW: { flowRate: 0, nodes: ["DT", "QT"] },
  CN: { flowRate: 0, nodes: ["OI", "RN"] },
  IU: { flowRate: 0, nodes: ["DY", "CV"] },
  LS: { flowRate: 0, nodes: ["CD", "UE"] },
  AA: { flowRate: 0, nodes: ["CH", "KC", "YM", "ZV", "GI"] },
  DY: { flowRate: 23, nodes: ["IU", "ZP"] },
  BS: { flowRate: 0, nodes: ["MJ", "KW"] },
  XG: { flowRate: 0, nodes: ["TU", "BO"] },
  RH: { flowRate: 15, nodes: ["HK", "JO", "CI"] },
  BO: { flowRate: 18, nodes: ["MY", "XG", "RR"] },
  YA: { flowRate: 0, nodes: ["OU", "HK"] },
  VS: { flowRate: 0, nodes: ["OI", "ER"] },
  KW: { flowRate: 6, nodes: ["BS", "XH", "GY", "HH", "FO"] },
  XH: { flowRate: 0, nodes: ["ZB", "KW"] },
  ZP: { flowRate: 0, nodes: ["DY", "DI"] },
  QL: { flowRate: 0, nodes: ["DI", "IG"] },
  GI: { flowRate: 0, nodes: ["HH", "AA"] },
  DT: { flowRate: 24, nodes: ["RW"] },
  DI: { flowRate: 13, nodes: ["OP", "ZP", "JO", "QL"] },
  QT: { flowRate: 0, nodes: ["RW", "KL"] },
  XM: { flowRate: 0, nodes: ["QA", "MJ"] },
  HK: { flowRate: 0, nodes: ["RH", "YA"] },
  TO: { flowRate: 19, nodes: ["NZ", "IG", "BC", "CV"] },
}

export const sample = {
  AA: { flowRate: 0, nodes: ["DD", "II", "BB"] },
  BB: { flowRate: 13, nodes: ["CC", "AA"] },
  CC: { flowRate: 2, nodes: ["DD", "BB"] },
  DD: { flowRate: 20, nodes: ["CC", "AA", "EE"] },
  EE: { flowRate: 3, nodes: ["FF", "DD"] },
  FF: { flowRate: 0, nodes: ["EE", "GG"] },
  GG: { flowRate: 0, nodes: ["FF", "HH"] },
  HH: { flowRate: 22, nodes: ["GG"] },
  II: { flowRate: 0, nodes: ["AA", "JJ"] },
  JJ: { flowRate: 21, nodes: ["II"] },
}
